import { releaseDownloadPath } from "./releases";

export type Platform = {
  name: string;
  status: "공개" | "완료" | "TestFlight" | "개발 중" | "준비 중";
  detail: string;
  url?: string;
  downloadLabel?: string;
  checksum?: string;
  availabilityNote?: string;
};

export type AppData = {
  slug: string;
  name: string;
  english: string;
  eyebrow: string;
  tagline: string;
  summary: string;
  theme: "violet" | "coral" | "amber" | "blue";
  icon?: string;
  heroImage?: string;
  spotlightImage?: string;
  systemImage?: string;
  artwork: "files" | "phones" | "clock" | "menubar" | "cleanup" | "trackpad" | "thumbnail" | "htoms" | "search" | "church" | "server" | "intelligence" | "bridge";
  platforms: Platform[];
  features: { title: string; body: string; icon?: string }[];
  guide: { title: string; body: string }[];
  progress: { state: "done" | "active" | "next"; title: string; body: string }[];
  screenshots?: { src: string; alt: string; layout?: "phone" | "menu" | "landscape" | "tv" | "wide" | "square" }[];
  github: string[];
  privacy: string[];
  matchup?: {
    metrics: { value: string; label: string }[];
    scope: string[];
    note: string;
  };
};

export const apps: AppData[] = [
  {
    slug: "nasfinder",
    name: "나스파인더",
    english: "NasFinder",
    eyebrow: "YOUR STORAGE, WITHIN REACH",
    tagline: "내 저장공간을, 모든 기기에서.",
    summary: "NAS·클라우드·네트워크 장비와 기기 안의 파일을 한곳에서 보고 재생합니다. 폰하드·Live Photo↔Motion Photo 전송까지 이어지는 파일 앱입니다.",
    theme: "violet",
    icon: "/apps/nasfinder/icon.png",
    artwork: "files",
    platforms: [
      { name: "iPhone · iPad", status: "TestFlight", detail: "2.2.2 (202608271227) · iOS·iPadOS 17+", availabilityNote: "공개 링크 유지 · 새 빌드 Apple 외부 베타 심사 대기" },
      {
        name: "Mac용 NasFinder",
        status: "공개",
        detail: "2.2.2 (202608271227) · macOS 14+ · Universal · Apple 공증 완료",
        url: releaseDownloadPath("NasFinder-Mac"),
        downloadLabel: "Mac용 DMG 바로 받기",
        checksum: "d8c4efb8a75a390f07a68c568abff3d4801b0a0d80bd538b9aad4bf442ff4554",
        availabilityNote: "Developer ID 서명 · Apple 공증 · Gatekeeper 확인",
      },
      {
        name: "Android",
        status: "공개",
        detail: "2.2.1 · 빌드 202608262056 · 내부 코드 342536 · Android 8.0+",
        url: releaseDownloadPath("NasFinder-Android"),
        downloadLabel: "Android APK 바로 받기",
        checksum: "d404e0f9275a2c604e4ecc99f9aaf65bcda448060a42b36e6444096fb3ce5aa6",
        availabilityNote: "27,948,170바이트 · SM-F968N 데이터 유지 교체 설치·실행 확인",
      },
    ],
    features: [
      { title: "여러 저장공간을 한곳에서", body: "Synology, SFTP, SMB, WebDAV, FTP와 Dropbox·OneDrive·Google Drive를 한 앱에서 탐색합니다." },
      { title: "로고 대신 내용이 보이는 Super Thumbnail", body: "영상 전체 길이의 3/13 지점을 먼저 고르고, 화면 절반 이상이 검을 때만 6/13 지점을 한 번 더 확인합니다. 폴더는 최대 9칸으로 모으며 살색 비율 20%까지는 선명하게, 그 이상은 최대 2.5pt까지 한 번만 부드럽게 처리합니다. NAS Vault에 준비된 결과가 있으면 일반 썸네일보다 먼저 보여줍니다." },
      { title: "즐겨찾기도 폴더 표지로 한눈에", body: "Android에서는 NAS·OneDrive·Google Drive의 이전 항목까지 썸네일을 되찾아 보여줍니다. iPhone·iPad·Mac은 준비된 폴더 Super Thumbnail을 먼저 보여주고, 없을 때만 폴더 안 미디어 모자이크와 폴더 아이콘 순서로 안전하게 돌아갑니다. 길게 눌러 제거하고 드래그해 원하는 순서로 정리할 수 있습니다." },
      { title: "움직임과 재생 흐름이 끊기지 않게", body: "움직이는 GIF를 미디어 보기에서 그대로 재생하고, 영상 준비 상태는 진행률을 알 수 있을 때와 없을 때 모두 이어서 표시합니다. 재생 중에는 1% 단위 볼륨과 35% 투명도의 1dp 흑백 하단 선으로 세밀하게 확인합니다." },
      { title: "민감할 수 있는 썸네일은 기기 안에서 완화", body: "Android가 썸네일을 기기 안에서만 살펴 살색 영역이 절반 이상이면 2dp 블러를 적용합니다. 분석 결과나 원본 이미지는 별도 서버로 보내지 않습니다." },
      { title: "Live Photos & Motion Photos", body: "사진·영상·Live Photo·Motion Photo를 함께 고르고 QR로 연결하면 상대 기기에 맞게 원본을 보존하거나 자동 변환해 사진 보관함에 저장합니다." },
      { title: "파일 작업을 자연스럽게", body: "연결이 지원하는 범위에서 업로드, 폴더 생성, 이름 변경, 복사·이동·삭제까지 처리합니다." },
      { title: "기기 안에서 안전하게", body: "Apple 기기는 Keychain, Android는 Keystore로 비밀번호와 로그인 토큰을 보호하고 폰하드 파일과 캐시는 앱 전용 저장공간에 보관합니다." },
      { title: "폰하드로 모으고 관리", body: "브라우저·네트워크·폰하드로 받은 파일을 기기 안의 한 공간에서 보고 관리합니다. 같은 화면 위에서 서버를 열어 다른 기기의 파일도 받습니다.", icon: "/apps/nasfinder/phone-hard.png" },
      { title: "파일 앱에서 바로 가져오기", body: "iPhone·iPad의 파일 앱과 Android 시스템 파일 선택기에서 여러 파일을 골라 폰하드에 안전하게 복사합니다." },
      { title: "Google Photos에서 직접 선택", body: "iPhone·iPad와 Android용 Google Photos Picker 가져오기 소스가 구현되어 있습니다. 사용자가 직접 고른 사진·영상만 폰하드로 내려받는 흐름이며, 실제 Google 계정 검증이 끝나기 전에는 공개 완료 기능으로 표시하지 않습니다." },
      { title: "외부 파일 앱과 자연스럽게", body: "iPhone·iPad의 파일 앱과 Android 시스템 파일 탐색기에서 지원 연결을 NasFinder 위치로 열고, 다른 파일 탐색기의 ‘다음으로 열기’에서 받은 파일도 NasFinder의 공통 미디어 보기로 이어지는 소스가 반영되어 있습니다. 다음 공개판 전 기기 검증 중입니다." },
      { title: "화면에 맞춰 커지는 Overflow", body: "자세히·썸네일·포스터 중에서 고르고, 넓은 화면에서는 Overflow로 자연스럽게 이어집니다. 2.1.0은 휴대전화·태블릿·폴더블의 실제 안전영역을 기준으로 중앙 정사각형과 앞뒤 카드를 배치하고, 기기 상태 표시를 숨기며, 오른쪽 메뉴에서 보기와 배경을 함께 바꾸고 왼쪽 화살표를 길게 눌러 첫 화면으로 돌아가도록 반영했습니다." },
      { title: "BK Style과 기기별 아이콘", body: "iPhone·iPad에서는 테마와 어울리는 여섯 가지 앱 아이콘을 고를 수 있습니다. Mac에서는 지원되지 않는 아이콘 변경과 반복 경고를 없애고 한 아이콘을 유지하며, 테마와 2배 크기 화면은 그대로 적용됩니다." },
    ],
    guide: [
      { title: "연결 추가", body: "서비스를 선택하고 서버 주소와 계정을 입력하거나 OAuth로 로그인한 뒤 연결을 확인합니다." },
      { title: "탐색과 미리보기", body: "저장한 NAS를 누르면 루트부터 새로 시작합니다. 다른 앱을 사용한 뒤 돌아오면 첫 화면에서 다시 시작해 현재 위치를 헷갈리지 않게 하고, 사진·영상·움직이는 GIF·PDF·일반 문서를 앱 안에서 확인합니다." },
      { title: "폰하드와 전송", body: "다른 앱의 공유 메뉴나 시스템 파일 선택기에서 가져온 파일을 폰하드에 보관하고, 원하는 NAS 위치로 전송합니다." },
      { title: "기기 간 미디어 전송", body: "보낼 미디어를 썸네일과 종류·영상 길이로 확인하고 필요 없는 항목을 뺀 뒤, 받을 기기의 QR을 스캔해 전송합니다. 받는 쪽은 QR만 표시하면 됩니다." },
      { title: "데이터 관리", body: "연결 삭제, 폰하드 파일 삭제와 캐시 정리를 할 수 있고, 설정에서 Google Photos를 Google Drive와 별도로 연결 해제할 수 있습니다." },
      { title: "앱 정보 확인", body: "설정에서 만든 사람과 공식 홈페이지를 확인하고, 오픈소스 구성요소는 실제 라이선스와 원문 링크가 있는 공개 페이지에서 살펴봅니다." },
    ],
    progress: [
      { state: "done", title: "핵심 탐색과 미리보기", body: "다양한 원격 저장소 탐색, 미디어 썸네일과 미리보기 구현" },
      { state: "active", title: "실제 환경 검증", body: "서버별 파일 작업, 파일 앱 연동과 네트워크 예외를 검증 중" },
      { state: "active", title: "Google Photos Picker", body: "iPhone·iPad와 Android에서 사용자가 Picker로 직접 선택한 사진·영상만 폰하드로 가져오는 소스 구현 완료 · 실제 Google 계정 검증 대기" },
      { state: "done", title: "iPhone·iPad·Mac 지원", body: "iPhone과 iPad 앱 완성, 동일 앱의 Apple Silicon Mac 설치와 실행 검증" },
      { state: "done", title: "Live Photo·Motion Photo 전송", body: "iPhone과 Android를 QR로 연결해 사진·영상·움직이는 사진의 원본 보존과 교차 변환 구현" },
      { state: "active", title: "iPhone·iPad 2.2.2 Public Beta", body: "build 202608271227 처리 완료 · 기존 내부 그룹 9명 보존 · 10,000명 공개 링크 유지 · 새 빌드 Apple 외부 베타 심사 대기 중" },
      { state: "done", title: "Mac용 NasFinder 2.2.2 공개", body: "즐겨찾기 폴더 표지와 살색 비율별 최대 2.5pt 처리를 반영한 Universal DMG를 Developer ID로 서명하고 Apple 공증·Gatekeeper 확인 후 공개" },
      { state: "done", title: "Android 2.2.1 공개", body: "즐겨찾기 썸네일·정렬, 움직이는 GIF, 세밀한 영상 제어와 준비 진행 표시, 민감 썸네일 완화, 앱 복귀 흐름을 반영한 빌드 202608262056 · 내부 코드 342536의 서명 APK를 공개하고 SM-F968N에 설치·실행 확인" },
      { state: "done", title: "Super Thumbnail 2.2.0 동기화", body: "3/13 대표 장면, 50% 검은 화면의 6/13 재시도, 최종 1.5pt 단일 블러와 우선 표시를 Apple·Android·Mac에 반영" },
    ],
    screenshots: [
      { src: "/apps/nasfinder/screens/iphone-favorites-folder-thumbnails.png", alt: "나스파인더 iPhone 즐겨찾기에서 폴더 Super Thumbnail이 표시된 화면" },
      { src: "/apps/nasfinder/screens/android-home.png", alt: "나스파인더 Android 저장공간 홈" },
      { src: "/apps/nasfinder/screens/android-received.png", alt: "나스파인더 Android 폰하드" },
      { src: "/apps/nasfinder/screens/android-add-connection.png", alt: "나스파인더 Android 연결 추가" },
      { src: "/apps/nasfinder/screens/android-thumbnail-cache.png", alt: "나스파인더 Android 썸네일 캐시 관리" },
      { src: "/apps/nasfinder/screens/android-theme.png", alt: "나스파인더 Android 테마와 앱 아이콘" },
      { src: "/apps/nasfinder/screens/android-super-thumbnail.png", alt: "나스파인더 Android Super Thumbnail" },
    ],
    github: ["https://github.com/armsone/NasFinder", "https://github.com/armsone/NasFinder-Android"],
    privacy: [
      "Apple 앱은 연결 정보를 App Group에, 비밀번호·세션·OAuth 자격증명을 Keychain에 저장합니다. Android 앱은 자격증명을 Android Keystore로 보호한 기기 전용 저장공간에 보관합니다.",
      "폰하드 파일과 썸네일 캐시는 사용자의 기기 안에 저장됩니다.",
      "Google Photos Picker 가져오기 소스는 사용자가 직접 선택한 사진·영상만 iPhone·iPad와 Android의 폰하드로 내려받고 전체 보관함을 탐색하지 않도록 구현되어 있습니다. OAuth 토큰은 Apple 기기의 Keychain과 Android Keystore로 보호한 앱 전용 저장공간에 각각 보관하도록 구현했으며, 실제 Google 계정 검증은 아직 완료되지 않았습니다.",
      "기기 간 미디어 전송은 같은 로컬 네트워크에서 두 기기가 직접 연결되며 별도 중계 서버로 사진과 영상을 보내지 않습니다.",
      "사용자가 선택한 외부 저장소 서비스와 직접 통신하며 각 서비스의 정책이 함께 적용됩니다.",
    ],
  },
  {
    slug: "super-thumbnail",
    name: "수퍼썸네일 for Mac",
    english: "Super Thumbnail",
    eyebrow: "PREPARE ON MAC, BROWSE IN NASFINDER",
    tagline: "큰 미디어 폴더의 미리보기를, Mac에서 미리.",
    summary: "Finder에 연결한 NAS 또는 Mac 폴더를 직접 읽어 NasFinder와 호환되는 수퍼썸네일을 대량으로 만드는 macOS 전용 앱입니다.",
    theme: "violet",
    icon: "/apps/super-thumbnail/icon.png",
    artwork: "thumbnail",
    platforms: [
      {
        name: "macOS",
        status: "공개",
        detail: "2.3.2 (202608291428) · macOS 14+ · Apple Silicon·Intel · Developer ID 서명·Apple 공증 완료",
        url: releaseDownloadPath("NasFinder-Super-Thumbnail"),
        downloadLabel: "Mac용 DMG 바로 받기",
        checksum: "7c0c02bb250a3720e0957ed5361ec811ccfbdbd0dc4398cff0287208f5ec7eb2",
      },
    ],
    features: [
      { title: "폴더는 차례대로, 파일은 동시에", body: "여러 폴더를 한 번에 작업 대기열에 등록합니다. 폴더 작업은 충돌 없이 차례대로 진행하고, 각 폴더 안의 사진과 영상은 여러 작업자가 동시에 수퍼썸네일로 만듭니다." },
      { title: "원하는 속도, 발열에는 자동 대응", body: "자동 체크박스를 켜고 −/+ 버튼으로 1~16개 작업자를 정합니다. Mac이 뜨거워지면 절반, 위험 수준이면 1개로 줄였다가 식으면 다시 늘리며, 폴더는 적용 중인 파일 작업자 수의 절반(최소 1개)으로 처리합니다." },
      { title: "찾는 동안 발견 수까지", body: "사진·영상과 하위 폴더를 찾는 동안 큰 검색 애니메이션과 진행 막대에 발견한 폴더 수와 파일 수가 실시간으로 나타납니다." },
      { title: "내용을 고르는 대표 장면", body: "영상 전체 길이의 3/13 지점을 사용하고 화면 절반 이상이 검을 때만 6/13을 한 번 더 확인해 시작 로고만 반복되는 결과를 줄입니다." },
      { title: "폴더도 9칸, 흐림은 꼭 필요한 만큼만", body: "파일과 하위 폴더를 최대 9개 골라 정사각형 모아보기로 만듭니다. 살색 비율 20%까지는 선명하게 유지하고 그 이상은 최대 2.5pt까지 부드럽게 조절하며, 상위 폴더에서도 흐림이 겹치지 않게 딱 한 번만 적용합니다." },
      { title: "NasFinder와 바로 호환", body: "iPhone·iPad·Mac·Android NasFinder가 읽을 수 있는 JPEG 이름과 .NasFinder-Vault 저장 구조를 사용합니다." },
      { title: "미리보는 재미까지 크게", body: "선택한 폴더의 기존 썸네일과 새로 만들어지는 결과를 앱 안에서 확인합니다. 가로 손잡이를 아래로 끌수록 미리보기와 이미지가 함께 커지고, 고른 크기도 기억합니다. 새로 만든 항목이 가장 왼쪽에 나타납니다." },
      { title: "중단 후 이어서", body: "이미 만든 썸네일은 건너뛰고 다시 검사하므로 긴 작업을 멈췄다가 안전하게 이어갈 수 있습니다." },
      { title: "원본은 그대로, 썸네일만 새로", body: "새로하기는 선택한 폴더 아래의 .NasFinder-Vault만 확인 후 지우고 다시 만듭니다. 사진과 영상 원본은 삭제하지 않습니다. 보관본을 찾을 때부터 삭제 완료 개수까지 큰 진행 막대로 보여줍니다." },
      { title: "진행 상태를 한눈에", body: "전체 파일 수, 완료 수, 예상 남은 시간, 확인한 원본 용량과 생성된 썸네일 용량을 표시합니다." },
      { title: "Mac에서 직접 처리", body: "파일을 개발자 서버로 보내지 않고 사용자가 선택한 Finder 폴더를 Mac에서 직접 읽고 씁니다." },
    ],
    guide: [
      { title: "앱 설치", body: "공식 DMG를 열고 NasFinder Super Thumbnail을 응용 프로그램 폴더로 옮깁니다." },
      { title: "NAS 연결", body: "Finder에서 사용할 NAS 공유 폴더를 먼저 연결합니다. Mac 내부 미디어 폴더도 선택할 수 있습니다." },
      { title: "작업 폴더 등록", body: "앱에서 폴더 선택을 누르고 사진과 영상이 들어 있는 폴더를 하나 또는 여러 개 고릅니다. 여러 폴더는 작업 대기열에서 순서대로 처리됩니다." },
      { title: "속도와 생성 방식 선택", body: "자동 체크박스와 −/+ 버튼으로 동시 작업자 수를 1~16개 사이에서 정합니다. 이어하기로 남은 작업을 계속하거나 새로하기로 선택한 폴더의 Vault 썸네일만 다시 만듭니다." },
      { title: "NasFinder에서 보기", body: "작업을 마친 뒤 NasFinder에서 같은 NAS 폴더를 열면 준비된 수퍼썸네일을 사용합니다." },
    ],
    progress: [
      { state: "done", title: "Mac 전용 네이티브 앱", body: "Finder 폴더 선택, 재귀 검색, 생성·일시정지·중단과 이어하기 구현" },
      { state: "done", title: "대규모 폴더 검증", body: "16,540개 미디어·1.57TB 폴더의 검색, 진행률과 용량 표시 검증" },
      { state: "done", title: "2.1.1 공개 배포", body: "build 202608251305의 Universal DMG를 Developer ID 서명·Apple 공증·Gatekeeper 검증 후 공개하고 자동 업데이트 반영" },
      { state: "done", title: "2.1.2 정리 진행과 미리보기 개선", body: "보관본 탐색·삭제 진행 막대와 최신 항목이 왼쪽에 오는 iPhone형 가로 미리보기를 서명·공증한 Universal DMG로 공개" },
      { state: "done", title: "2.1.3 사진·영상 찾기 진행 표시", body: "큰 검색 애니메이션과 진행 막대, 파일·하위 폴더별 안내를 추가한 Universal DMG를 서명·공증해 공개" },
      { state: "done", title: "2.1.4 크기 조절 미리보기", body: "아래로 끌면 이미지가 함께 커지는 가로 미리보기와 선택 크기 기억 기능을 서명·공증한 Universal DMG로 공개" },
      { state: "done", title: "2.2.0 대표 장면과 단일 블러", body: "3/13 대표 장면과 조건부 6/13 재시도, 최종 1.5pt 단일 블러를 Developer ID 서명·Apple 공증한 Universal DMG로 공개" },
      { state: "done", title: "2.3.1 실시간 발견 수와 유연한 병렬 처리 공개", body: "폴더·파일 실시간 발견 수, 자동 체크박스와 안정적인 −/+ 1~16개 조절, 발열 감축·복귀와 파일 동시 수의 절반을 쓰는 폴더 처리를 Developer ID 서명·Apple 공증한 Universal DMG로 공개" },
      { state: "done", title: "2.3.2 단계형 폴더 흐림 공개", body: "살색 비율 20%까지는 선명하게 유지하고 그 이상은 최대 2.5pt까지 단계적으로 처리하며, 중첩 폴더에서도 흐림이 겹치지 않는 Universal DMG를 Developer ID 서명·Apple 공증해 공개" },
      { state: "active", title: "다양한 NAS 환경 확인", body: "Finder 연결 방식과 파일 권한에 따른 예외를 계속 점검 중" },
    ],
    github: ["https://github.com/armsone/SuperThumbnail-MacOS"],
    privacy: [
      "사용자가 직접 선택한 Finder의 NAS 또는 Mac 폴더만 읽고 썸네일을 생성합니다.",
      "생성한 JPEG는 원본 폴더 안의 .NasFinder-Vault에 저장되며 개발자 서버로 전송하지 않습니다.",
      "마지막으로 선택한 폴더 경로는 다음 작업을 이어가기 위해 Mac의 앱 설정에 저장될 수 있습니다.",
    ],
  },
  {
    slug: "hanclip",
    name: "한클립",
    english: "HanClip",
    eyebrow: "MOMENTS INTO A MOVIE",
    tagline: "고르는 순간부터, 한 편의 영화까지.",
    summary: "사진과 영상, Live Photo를 고르면 복잡한 편집을 줄여 한 편의 MP4 영화로 만드는 iPhone·iPad·Apple Silicon Mac·Android 앱입니다.",
    theme: "coral",
    icon: "/apps/hanclip/icon.png",
    artwork: "phones",
    platforms: [
      { name: "iOS · iPadOS", status: "TestFlight", detail: "2.2.1 (202608251900) · iOS·iPadOS 17+", availabilityNote: "Public Beta 승인 · 공개 테스트 참여 가능" },
      { name: "Mac", status: "TestFlight", detail: "2.2.1 · Apple Silicon · iPad 앱 호환 모드", availabilityNote: "같은 TestFlight 빌드 · 공개 테스트 심사 중" },
      {
        name: "Android",
        status: "공개",
        detail: "2.2.1 · 빌드 202608251900 · 내부 코드 340980 · Android 8.0+",
        url: releaseDownloadPath("HanClip-Android"),
        downloadLabel: "Android APK 바로 받기",
        checksum: "f4b607c0d5b860c4dd1c42a24f653b0bacf5f17d9b10684307af33eec102201b",
        availabilityNote: "서명 APK 재다운로드·무결성 검증 완료 · 휴대전화·태블릿·Google TV 지원",
      },
    ],
    features: [
      { title: "빠른 영화 만들기", body: "실제 장면 수와 영상 분량에 맞춰 시간을 고르게 배분하고, 엔딩을 포함한 완성시간을 음악 길이에 맞춘 뒤 결과를 다듬습니다." },
      { title: "AiShot", body: "Apple과 Android에서 골프 스윙의 준비·동작·임팩트와 타격음을 함께 살핍니다. 소리가 거의 없는 퍼팅은 준비 자세부터 작은 백스윙·전진·팔로스루까지 몸동작 순서가 확실하고 화면이 안정적일 때만 보수적으로 촬영합니다." },
      { title: "무음 영상도 장면 분석", body: "타임랩스·슬로 모션처럼 오디오 트랙이 없는 영상은 화면 움직임을 분석하고, 뚜렷한 변화가 없으면 영상 중앙을 기준으로 하이라이트를 제안합니다." },
      { title: "장면을 내 방식으로", body: "순서, 길이, 화면비, 자막과 음악, 워터마크와 엔딩 카드를 조절합니다." },
      { title: "사진부터 Live Photo까지", body: "사진·영상·Live Photo와 Android Motion Photo, 파일과 공유 항목을 가져옵니다." },
      { title: "시사회 후 결정", body: "완성된 영화를 먼저 확인한 뒤 다시 편집하거나 사진 앱·갤러리·파일로 저장합니다." },
      { title: "개봉영화 보관함", body: "새로 완성한 영화는 최대 30편까지 앱 안에 따로 보관합니다. 영화를 길게 눌러 컬렉션에도 바로 추가하고, 개봉영화 원본은 그대로 남길 수 있습니다." },
      { title: "프로젝트 보관", body: "만들던 영화와 컬렉션을 저장해 다음에 이어서 작업할 수 있습니다." },
      { title: "Mac에서도 이어서", body: "Apple Silicon Mac에서 iPad 앱 호환 모드로 실행해 트랙패드와 키보드로 같은 영화 제작 흐름을 사용합니다." },
      { title: "찾기 쉬운 테마와 저작권", body: "테마 설정을 카피라이트보다 먼저 보여주고, 긴 저작권 설명은 필요한 제목을 눌렀을 때만 펼쳐 봅니다. 워터마크 사용 여부도 한 줄 어디서나 쉽게 조작합니다." },
    ],
    guide: [
      { title: "프리셋 선택", body: "새 영화, 퀵모드, AiShot 또는 여행·인생·골프 프리셋에서 시작합니다." },
      { title: "미디어 가져오기", body: "사진첩·갤러리·달력·파일이나 다른 앱의 공유 메뉴에서 재료를 고릅니다." },
      { title: "편집과 만들기", body: "자동 묶음과 분할 결과를 확인하고 자막·음악·로고를 더해 영화를 만듭니다." },
      { title: "저장과 공유", body: "시사회에서 결과를 살핀 뒤 기기에 저장하거나 원하는 앱으로 공유합니다." },
    ],
    progress: [
      { state: "done", title: "iOS 핵심 제작 흐름", body: "선택, 편집, 렌더링, 시사회와 저장 흐름 구현" },
      { state: "active", title: "iOS·iPadOS 2.2.1 업로드", body: "build 202608251900을 TestFlight에 업로드하고 Apple 처리를 기다리는 중" },
      { state: "done", title: "Android 2.2.1 공개", body: "제품 2.2.1 · 빌드 202608251900 · 내부 코드 340980의 서명 APK를 GitHub Releases에 공개" },
      { state: "done", title: "플랫폼 기술 계약 동기화", body: "기능·알고리즘·상태·오류·취소·권한·제스처·접근성 계약을 Apple과 Android에 대조 반영" },
      { state: "active", title: "Android AiShot 현장 검증", body: "실제 퍼팅과 다양한 스윙 환경에서 놓침과 오촬영을 계속 점검 중" },
      { state: "done", title: "Apple Silicon Mac 지원", body: "iPhone·iPad와 같은 빌드를 Mac의 ‘iPhone 및 iPad용 앱’으로 실행하도록 지원" },
      { state: "done", title: "AiShot 동작 인식 강화", body: "소리 단독 반응을 줄이고 화면 움직임과 기기 내 신체 자세 분석을 결합" },
      { state: "done", title: "Apple·Android 무음 퍼팅 안전망", body: "타구음 없이도 준비 자세부터 팔로스루까지 완성된 퍼팅 동작을 보수적으로 판정" },
      { state: "active", title: "현장 감도 검증", body: "풀스윙뿐 아니라 대표성 있는 퍼팅 영상으로 놓침과 오촬영을 추가 검증할 예정" },
    ],
    screenshots: [
      { src: "/apps/hanclip/screens/ios-home.png", alt: "한클립 iOS 홈" },
      { src: "/apps/hanclip/screens/ios-add-media.png", alt: "한클립 iOS 미디어 추가" },
      { src: "/apps/hanclip/screens/android-quick-select.png", alt: "한클립 Android 퀵모드 사진 선택" },
      { src: "/apps/hanclip/screens/android-duration.png", alt: "한클립 Android 장면 길이 설정" },
      { src: "/apps/hanclip/screens/android-editor-pets.png", alt: "고양이와 강아지 사진으로 꾸민 한클립 Android 편집 화면" },
      { src: "/apps/hanclip/screens/android-home-dark.png", alt: "한클립 Android 다크 모드 홈" },
      { src: "/apps/hanclip/screen-home.png", alt: "한클립 영화 만들기 홈" },
      { src: "/apps/hanclip/screen-preview.png", alt: "한클립 완성 영화 미리보기" },
      { src: "/apps/hanclip/screen-ratios.png", alt: "한클립 영화 화면비 선택" },
    ],
    github: ["https://github.com/armsone/HanClip", "https://github.com/armsone/HanClip-Android"],
    privacy: [
      "사용자가 고른 사진·영상·음원과 프로젝트 정보는 영화 제작을 위해 처리합니다.",
      "카메라와 마이크는 AiShot에서 순간을 감지하고 촬영할 때 사용하며, 화면 움직임과 신체 자세 분석은 기기 안에서 처리합니다.",
      "기기에 내보낸 완성본은 앱을 삭제해도 남을 수 있으므로 사진 앱·갤러리에서 별도로 삭제해야 합니다.",
    ],
  },
  {
    slug: "hanai",
    name: "한양",
    english: "HANYANG",
    eyebrow: "YOUR DIGITAL CAPITAL",
    tagline: "나의 디지털 수도.",
    summary: "한양은 한 사람의 기억과 정보, 도구가 한곳에 모여 함께 움직이도록 설계하는 개인용 AI 프로젝트입니다. 600년 전 한 나라를 운영하기 위해 세운 계획도시에서 착안해, 지금은 미디어 지능을 기기 안에서 다듬고 앞으로 기억·정리·판단·안전한 실행을 하나의 질서로 연결합니다.",
    theme: "violet",
    icon: "/apps/hanai/icon.png",
    heroImage: "/apps/hanai/hanyang-city-hero-v3.png",
    spotlightImage: "/apps/hanai/hanyang-memory-archive-v1.png",
    systemImage: "/apps/hanai/hanyang-secure-gates-v1.png",
    artwork: "intelligence",
    platforms: [
      {
        name: "Swift Package",
        status: "공개",
        detail: "0.2.0 · Golf 모델 0.7.0 · Foundation 기반 독립 코어",
        url: "https://github.com/armsone/HanAI/releases/tag/v0.2.0",
        downloadLabel: "HANYANG 0.2.0 소스 릴리즈 보기",
        availabilityNote: "한양 독립 프로젝트로 공개 · 특정 앱에 병합하지 않음",
      },
      {
        name: "Kotlin/JVM",
        status: "공개",
        detail: "0.2.0 · Golf 모델 0.7.0 · Kotlin 표준 라이브러리 기반 독립 코어",
        url: "https://github.com/armsone/HanAI/releases/download/v0.2.0/hanai-core-0.2.0.jar",
        downloadLabel: "Kotlin/JVM 0.2.0 JAR 받기",
        checksum: "688a9f385bb4706ddfee4f79e4fe188da155bc7d76967191e76ab2debd992ad9",
        availabilityNote: "Swift와 같은 모델·상수·fixture 계약 · 공개 파일 무결성 확인",
      },
    ],
    features: [
      { title: "나를 중심으로 세워진 AI 도시", body: "범용 챗봇 하나를 더 만드는 대신, 한 사람의 기억·정보·도구가 사용자라는 중심을 향해 질서 있게 연결되는 개인 인공지능을 만듭니다." },
      { title: "도시처럼 연결되는 개인 AI", body: "대화와 알림이 오가는 길, 지식을 보관하는 공간, 전문 에이전트와 외부 서비스의 관문을 하나의 구조 안에서 연결하는 것이 한양의 방향입니다." },
      { title: "한양도성처럼 분명한 경계", body: "개인 데이터와 외부 세계의 경계를 먼저 세웁니다. 원본 영상·사진·프레임·오디오·관절 좌표는 기기 또는 로컬에서만 처리합니다." },
      { title: "전통이 아니라 도시 철학", body: "기와·붓글씨 같은 복고 장식을 앞세우지 않습니다. 화면은 현대적이고 직관적으로 유지하고, 한양의 계획도시 개념은 정보 구조와 시스템 설계에 담습니다." },
      { title: "현재는 미디어 지능부터", body: "화면 움직임과 자세 흐름, 소리의 특징을 함께 살펴 사진·영상 속 의미 있는 순간을 보수적으로 이해하는 독립 코어를 다듬고 있습니다." },
      { title: "비슷한 사진은 줄이고 좋은 장면은 남기기", body: "사진 원본 대신 선명도·크기·거리 같은 익명 수치만 받아 가까운 중복을 묶고, 그중 품질이 좋은 대표 사진을 Swift와 Kotlin에서 같은 기준으로 고릅니다." },
      { title: "기억에서 안전한 실행까지", body: "다음에는 사용자가 허용한 정보의 기억과 정리, 선택지 비교, 확인을 거친 일상 실행으로 차근차근 범위를 넓혀 갑니다." },
    ],
    guide: [
      { title: "브랜드는 한양 HANYANG", body: "사용자가 만나는 이름은 한양과 HANYANG입니다. 공개 저장소와 기존 코드 패키지는 호환성을 위해 현재 HanAI 식별자를 유지합니다." },
      { title: "도시 이름은 보이지 않게", body: "승정원·규장각·육조·사대문은 내부 세계관과 구조를 설명하는 언어입니다. 실제 화면에서는 기억·일정·파일·자동화처럼 바로 이해되는 이름을 사용합니다." },
      { title: "현재의 기반", body: "0.2.0과 Golf 모델 0.7.0은 Swift·Kotlin 독립 코어, 정규화된 특징과 교차 플랫폼 fixture를 제공합니다." },
      { title: "사용자가 경계를 결정", body: "무엇을 기억하고 어디까지 연결하며 어떤 행동을 실행할지는 사용자가 정합니다. 외부 전송과 되돌리기 어려운 행동은 분명히 구분하고 확인 뒤 진행합니다." },
    ],
    progress: [
      { state: "done", title: "독립 프로젝트 0.1.0 공개", body: "Swift·Kotlin 코어와 Golf 모델 0.7.0을 별도 GitHub Release로 공개하고 두 플랫폼 fixture 테스트를 확인" },
      { state: "done", title: "0.2.0 대표 사진 선택 공개", body: "가까운 중복을 줄이고 품질이 좋은 대표 사진을 남기는 동일한 Swift·Kotlin 계약을 검증해 소스 패키지와 Android JAR로 공개" },
      { state: "done", title: "한양 HANYANG 브랜드 정립", body: "한 사람의 기억과 정보, 도구가 모이는 ‘나의 디지털 수도’를 제품 정체성과 설계 언어로 확정" },
      { state: "active", title: "도시의 첫 기반, 미디어 지능", body: "사진·영상의 화면 움직임과 자세 흐름, 오디오 특징을 정규화해 의미 있는 순간을 기기 안에서 이해하는 기반을 다듬는 중" },
      { state: "next", title: "기억·정리·연결·실행", body: "사용자가 고른 정보의 장기 기억과 정리, 외부 서비스 연결, 판단 보조와 확인을 거친 안전한 실행으로 확장" },
    ],
    github: ["https://github.com/armsone/HanAI"],
    privacy: [
      "원본 영상·사진·프레임·오디오·관절 좌표는 기기 또는 로컬에서만 처리하며 저장소·로그·외부 서비스에 올리지 않습니다.",
      "검증 자료에는 정규화된 수치 특징과 라벨만 남기고 파일명, 촬영 시각, 위치, 사람·계정 식별 정보는 기록하지 않습니다.",
      "앞으로 기억과 실행 범위가 늘어나도 사용자가 허용한 정보와 행동만 다루고, 외부 전송과 되돌리기 어려운 행동은 분명히 구분합니다.",
    ],
  },
  {
    slug: "stand",
    name: "S.tand",
    english: "S.tand",
    eyebrow: "A QUIET COMPANION AT NIGHT",
    tagline: "낮에는 오브제, 밤에는 조용한 케어.",
    summary: "플립시계와 날씨를 보여주는 오브제이자, 밤에는 움직임에 불빛으로 반응하고 수면 소리 후보를 기록합니다. 라디오 채널은 파일로 옮기고 Google TV에는 같은 Wi-Fi의 휴대전화로 간편하게 전송할 수 있습니다.",
    theme: "amber",
    icon: "/apps/stand/icon.png",
    artwork: "clock",
    platforms: [
      { name: "iOS · iPadOS", status: "TestFlight", detail: "2.3.0 (202608282116) · iOS·iPadOS 17+", availabilityNote: "Public Beta 승인 · 공개 테스트 참여 가능" },
      {
        name: "macOS",
        status: "공개",
        detail: "2.3.0 (202608282116) · macOS 14+ · Apple 공증 완료",
        url: releaseDownloadPath("S.tand-macOS"),
        downloadLabel: "Mac용 DMG 바로 받기",
        checksum: "a3baaafab73c6f0f111e11e6bafe278164d52deaf9cd559a94dd22169b7b6480",
      },
      {
        name: "Android · Google TV",
        status: "공개",
        detail: "2.3.6 · 빌드 202608291816 · 내부 코드 346696 · Android 8.0+",
        url: releaseDownloadPath("S.tand-Android"),
        downloadLabel: "Android APK 바로 받기",
        checksum: "236cf24361d565ca9649b2e6c9e5df6710e0f7116efa318f88c94830cef56f35",
        availabilityNote: "Android·Google TV용 2.3.6 APK 공개 · TV 배터리·매이트 모드 정리 · 날씨 패널 확대와 시계 위치 조정 · TV 실기기 재확인 대기",
      },
    ],
    features: [
      { title: "오브제 모드", body: "플립시계, 날씨와 배터리를 가로·세로 화면에 차분하게 표시합니다." },
      { title: "매이트와 화들짝", body: "어두운 환경에서 최소 밝기를 유지하고, 매이트 모드 진입 2분 뒤부터 움직임이나 큰소리에 화면과 조명이 반응합니다." },
      { title: "로컬 수면 기록", body: "코골이·잠꼬대·뒤척임 후보를 기기 안에 기록하고 타임라인으로 확인합니다." },
      { title: "내 화면 만들기", body: "화면을 움직이지 않고 2초 동안 눌렀을 때만 편집을 엽니다. 가로 음량 조절이나 세로 밝기 조절 중에는 편집 모드로 바뀌지 않으며, 밝기·시계 글꼴·배치·테마를 화면 방향에 맞게 꾸밀 수 있습니다." },
      { title: "보이소", body: "QR로 볼 사람·말할 사람·무전기를 연결하고 Wi‑Fi·Bluetooth·인터넷 경로를 사람별로 한눈에 봅니다. 원음과 녹음은 보내지 않으며, 무전기는 버튼을 눌렀을 때만 연결된 화면을 부릅니다." },
      { title: "두 줄 음악·제어 카드", body: "음악과 잠소리·보이소·설정을 아이콘과 제목, 상태의 두 줄로 또렷하게 보여 줍니다. iPhone·iPad의 음악 카드는 왼쪽 절반으로 재생·일시정지하고 오른쪽 절반으로 다음 라디오나 다음 곡을 고르며, 음악 스트립을 밀면 채널 카드가 움직입니다." },
      { title: "라디오 프리셋 이동", body: "직접 등록한 HTTP·HTTPS 라디오 채널을 S.tand 파일로 내보내 다른 Apple·Android 기기에서 가져옵니다. Google TV에는 같은 Wi-Fi의 휴대전화로 QR 전송하며 외부 서버를 거치지 않습니다." },
      { title: "Google TV 리모컨 지원", body: "10-foot 가로 화면에서 D-pad로 음악·설정·테마·밝기·시계 크기를 조작합니다. 버튼을 눌러도 검은 배경이 생기지 않고 포커스 테두리만 또렷하게 보이며, 홈에서 뒤로가기를 누르면 앱이 정상 종료됩니다." },
      { title: "로고로 최신 버전 확인", body: "홈의 S.tand 로고를 누르면 현재 버전을 바로 확인합니다. iPhone·iPad는 TestFlight, Mac은 Sparkle, Android와 Google TV는 GitHub Releases의 최신 공개판을 확인합니다." },
      { title: "Apple Music 재생 제어", body: "Apple Music과 Classical의 재생 상태를 분리해 유지합니다. 카드 왼쪽 절반은 재생·일시정지를 바꾸고 오른쪽 절반은 다음 곡으로 넘기며, 멈춘 상태에서는 선택한 항목부터 재생합니다." },
      { title: "선택하는 백그라운드 동작", body: "백그라운드 모드는 권한 설정에서 켜고 끕니다. 기본값은 꺼짐이며, 꺼진 상태에서는 다른 앱으로 나갈 때 감지와 재생을 멈춥니다." },
      { title: "재현 가능한 화면 매치업", body: "한국어·서울 시간대·고정 시각 조건에서 iOS와 Android의 공통 화면 상태를 같은 의미 ID로 캡처하고 비교합니다." },
    ],
    guide: [
      { title: "권한 선택", body: "카메라·마이크·대략적 위치를 왜 사용하는지 확인하고 필요한 권한만 허용합니다." },
      { title: "세 가지 모드", body: "오브제, 매이트와 화들짝 모드의 역할과 밝기·제스처를 익힙니다." },
      { title: "화면 편집", body: "빈 화면을 움직이지 않고 2초 동안 누르면 편집 모드가 열립니다. 가로로 밀면 음량, 세로로 밀면 밝기가 조절되며 이때 편집 모드는 열리지 않습니다." },
      { title: "수면 기록", body: "날짜별 타임라인에서 후보 녹음을 듣고 병합·공유하거나 삭제합니다." },
      { title: "음악 채널", body: "Apple 기기에서는 Apple Music·Apple Music Classical과 인터넷 라디오 네 칸을, Android에서는 Spotify·YouTube Music과 인터넷 라디오 네 칸을 한 줄에서 좌우로 넘깁니다. iPhone·iPad 음악 카드는 왼쪽 절반이 재생·일시정지, 오른쪽 절반이 다음 라디오나 다음 곡이며 빈 라디오 카드는 전체를 눌러 등록합니다." },
      { title: "Google TV에서", body: "설정의 음악 항목에서 라디오 가져오기·내보내기 → 휴대전화에서 받기를 열고, 같은 Wi-Fi의 휴대전화로 QR을 스캔해 S.tand 라디오 파일을 보냅니다. 2.3.6에서는 배터리와 매이트 모드를 TV에서 정리하고 날씨를 1.5배 키웠으며, 검은 눌림 배경 없이 포커스 테두리만 보여 줍니다." },
      { title: "백그라운드 모드", body: "권한 설정의 세그먼트에서 켜짐 또는 꺼짐을 선택합니다. 기본 꺼짐은 앱을 벗어날 때 감지·재생을 중지하고, 필요할 때만 직접 켭니다." },
      { title: "보이소 연결", body: "공간을 만들고 QR로 참여해 볼 사람·말할 사람·무전기 역할을 선택합니다. 무전기는 주변 소리를 보내지 않고 호출 버튼을 눌렀을 때만 연결된 화면을 부릅니다." },
      { title: "Mac에서 시작", body: "공증된 DMG를 열고 S.tand를 응용 프로그램 폴더로 옮긴 뒤 실행합니다. 이후에는 앱이 업데이트를 확인하고 종료·교체 설치·재실행까지 이어서 처리합니다." },
    ],
    progress: [
      { state: "done", title: "시계와 수면 케어", body: "오브제 화면, 반응형 조명과 로컬 수면 기록 구현" },
      { state: "done", title: "iOS·iPadOS 2.3.0 Public Beta 승인", body: "build 202608282116 Apple 외부 베타 심사 승인 · 기존 Public Beta 링크와 10,000명 한도 유지 · 공개 테스트 참여 가능" },
      { state: "done", title: "Android·Google TV 2.3.6 공개", body: "TV 배터리·매이트 모드를 정리하고 검은 눌림 배경을 제거했으며, 날씨 패널을 1.5배 확대하고 시계를 함께 내린 빌드 202608291816 · 내부 코드 346696 APK 공개" },
      { state: "done", title: "Android·Google TV 2.3.5 공개", body: "보이소의 세 역할, 사람별 다중 연결 경로, 3초 연속 호출 방지와 선택적 종단간 암호화 인터넷 중계를 보강한 빌드 202608291507 · 내부 코드 346507 APK 공개" },
      { state: "done", title: "보이소 무전기", body: "주변 소리 없이 버튼으로 연결된 화면을 부르는 무전기 역할과 3초 연타 방지·고시인성 알림 적용" },
      { state: "done", title: "Mac 2.3.0 공개", body: "라디오 프리셋 가져오기·내보내기와 HTTP 주소 지원을 적용하고 Developer ID 서명·Apple 공증·실행 검증을 마친 build 202608282116 DMG 공개" },
      { state: "done", title: "휴대전화 가로 음악 배치", body: "iPhone 대표 가로 배치를 Android에도 적용하고 음악 스트립과 오른쪽 고정 제어 패널이 겹치지 않게 정리" },
      { state: "done", title: "Android 설정 화면 동기화", body: "인터넷 라디오 바로가기, 6개 음악 채널 통합 목록과 가로·태블릿 독립 패널 배치를 2.1.0에 반영" },
      { state: "done", title: "Google TV 공개", body: "TV 런처 배너, 음악·시계·날씨 중심 10-foot 화면과 D-pad 흐름을 Google TV API 36에서 검증해 공개" },
      { state: "done", title: "라디오 찾기 즐겨찾기", body: "앱 내 브라우저에 ‘내가 사랑하는 인터넷 라디오’ 안내 페이지를 기본 즐겨찾기로 추가" },
      { state: "next", title: "장시간 실기기 검증", body: "오디오·센서 흐름과 접근성을 다양한 기기에서 추가 검증" },
    ],
    screenshots: [
      { src: "/apps/stand/screens/android-home-two-line-cards.png", alt: "아이콘과 제목, 상태가 두 줄로 정렬된 S.tand Android 세로 홈 화면" },
      { src: "/apps/stand/screens/ios-home-portrait.png", alt: "큰 글자에서도 중앙 두 줄 음악 카드와 잠소리·보이소·설정 카드가 겹치지 않는 S.tand iOS 세로 오브제 시계" },
      { src: "/apps/stand/screens/ios-sleep-report.png", alt: "S.tand iOS 수면 기록 리포트" },
      { src: "/apps/stand/screens/android-editor.png", alt: "S.tand Android 내 화면 편집" },
      { src: "/apps/stand/screens/ios-home-landscape-flat.png", alt: "S.tand iOS 가로 오브제 시계", layout: "landscape" },
      { src: "/apps/stand/screens/android-recordings.png", alt: "S.tand Android 잠소리 관리" },
      { src: "/apps/stand/screens/ios-boyiso-walkie.png", alt: "볼 사람·말할 사람·무전기 역할을 고르는 S.tand iOS 보이소 연결 화면" },
      { src: "/apps/stand/screens/ios-clock-fonts.png", alt: "S.tand iOS 시계 글꼴 선택" },
      { src: "/apps/stand/screens/android-boyiso.png", alt: "S.tand Android 보이소 연결 화면" },
      { src: "/apps/stand/screens/android-settings-overview.png", alt: "S.tand Android 2.1.0 설정 화면과 상단 인터넷 라디오 바로가기", layout: "menu" },
      { src: "/apps/stand/screens/android-settings-music.png", alt: "Spotify·YouTube Music·인터넷 라디오를 한 목록에서 정렬하는 Android 음악 설정", layout: "menu" },
      { src: "/apps/stand/screens/google-tv-home.png", alt: "음악·서울 날씨·큰 시계와 리모컨 포커스가 보이는 S.tand Google TV 홈 화면", layout: "tv" },
    ],
    github: ["https://github.com/armsone/S.tand", "https://github.com/armsone/S.tand-Android"],
    privacy: [
      "수면 녹음은 앱 전용 저장공간에 보관되며 사용자가 공유할 때만 선택한 파일을 전달합니다.",
      "대략적 위치는 날씨를 가져올 때 사용하고, 카메라는 플래시와 주변 밝기 판단을 위해 사용합니다.",
      "Apple 기기의 Apple Music 기능은 사용자가 허용한 뒤 시스템 음악 플레이어와 MusicKit으로 현재곡·재생 상태, 보관함과 추천 항목을 조회합니다. S.tand는 Apple 계정의 로그인 정보나 암호를 저장하지 않습니다.",
      "의료용 진단 앱이 아니며 소리 분류 결과는 주변 환경에 따라 달라질 수 있습니다.",
    ],
    matchup: {
      metrics: [
        { value: "15", label: "iOS·Android 공통 상태" },
        { value: "11", label: "Android 실기기 카탈로그" },
        { value: "12", label: "iOS 정확 해시 안정 상태" },
      ],
      scope: [
        "첫 실행 권한과 홈 세로·가로·편집",
        "수면 리포트와 잠소리 관리",
        "보이소, 설정, 테마와 시계 글꼴",
        "인터넷 라디오 편집·삭제와 설정 복원",
        "폰트 저작권과 라이선스 전문",
      ],
      note: "기능·문구·주요 구조는 정렬했습니다. Android 실기기 카탈로그 11개 상태는 두 차례 모두 통과했으며, 트라이폴드 다중 디스플레이의 캡처 프레임 차이로 홈 세로 화면의 반복 해시는 후속 검증 항목입니다.",
    },
  },
  {
    slug: "ccmb",
    name: "CCMB",
    english: "CCMB",
    eyebrow: "AI USAGE AT A GLANCE",
    tagline: "Codex·Claude·Gemini 사용량을 메뉴 막대에서 한눈에.",
    summary: "터미널을 열지 않고도 Codex의 남은 주간 사용량·크레딧과 Claude·Gemini의 세션·주간 사용량을 대표 색상의 메뉴 막대 숫자와 3열 패널로 확인하는 비공식 macOS 앱입니다.",
    theme: "blue",
    icon: "/apps/ccmb/icon.png",
    artwork: "menubar",
    platforms: [
      { name: "macOS", status: "공개", detail: "2.0.12 (202608291047) · 내부 build 346247 · macOS 10.15+ · Universal · Apple 공증 완료", url: releaseDownloadPath("CCMB"), downloadLabel: "DMG 다운로드", checksum: "166e2a20998ba230100950cd242ab96fa5dbf3023fc3df3779c5324d55c4a90b" },
    ],
    features: [
      { title: "세 AI를 한눈에", body: "Codex·Claude·Gemini 사용량을 정밀 눈금·은은한 발광·끝점 표시가 있는 3열 링으로 나란히 확인합니다." },
      { title: "색으로 구분한 메뉴 막대 숫자", body: "아이콘 없이 남은 사용량 숫자만 표시하고 Codex·Claude·Gemini의 대표 색상으로 빠르게 구분합니다." },
      { title: "서비스별 스마트 갱신", body: "Codex·Claude·Gemini가 각각 1분으로 시작해 숫자가 그대로면 3분·5분·10분으로 조절되고, 사용량이 바뀌면 다시 1분으로 돌아옵니다." },
      { title: "같은 모양의 두 패널", body: "메뉴 막대에서 여는 패널과 항상 보기 패널에 같은 정보·간격·하단 설정을 제공합니다." },
      { title: "배경 불투명도", body: "두 패널의 전체 배경 불투명도를 95%~100% 범위에서 수치를 보며 조절합니다." },
      { title: "정렬된 계정·갱신 정보", body: "세 서비스의 요금제·계정 정보·상대 갱신 시각을 같은 기준선에서 비교합니다." },
      { title: "간결해진 하단 조작", body: "업데이트 확인과 현재 버전을 합치고 투명도, 재시작과 종료 조작을 같은 3열 그리드 안에 정돈했습니다." },
      { title: "로컬 공유", body: "최신성 근거가 포함된 로컬 JSON을 다른 앱과 Codex 대화에서 안전하게 읽습니다." },
      { title: "한 줄로 온전히 보이는 갱신 기록", body: "중복 서비스 이름과 말줄임표 없이 Spark·Fable을 포함한 갱신당 사용량을 한 줄로 표시하고, 막대 위 시각은 초 없는 24시간제로 보여 줍니다." },
      { title: "사라지지 않는 연결 복구", body: "응답 지연과 Mac의 잠자기·깨우기 뒤에도 앱을 종료하지 않고 데이터 연결만 안전하게 다시 시작합니다." },
      { title: "CCMB 전용 Claude 연결", body: "CCMB 안의 브라우저에서 Claude 계정을 한 번 연결합니다. Claude Code의 키체인 인증 정보를 읽지 않아 다른 앱의 승인 창이 반복되지 않습니다." },
      { title: "항상 자동인 서명 업데이트", body: "Sparkle과 GitHub Releases를 통해 새 버전을 자동으로 확인하고 내려받습니다. 수동 업데이트 확인도 남겨 두되 별도의 자동 다운로드 선택은 필요 없습니다." },
      { title: "로그인 시 시작", body: "선택하면 Mac 로그인과 함께 조용히 실행됩니다." },
    ],
    guide: [
      { title: "설치 준비", body: "macOS 10.15 이상과 로그인된 Codex CLI가 필요합니다. Claude는 CCMB 안에서 별도로 연결하고 Gemini는 Antigravity agy CLI의 기존 로그인을 활용합니다." },
      { title: "DMG로 설치", body: "GitHub Release에서 DMG를 받아 앱을 Applications 폴더로 옮깁니다." },
      { title: "표시와 새로고침", body: "메뉴 막대의 색상별 숫자와 상세 정보, 패널 배경 불투명도와 자동 새로고침 간격을 확인·설정합니다." },
      { title: "다른 대화와 공유", body: "로컬 ccmb-usage 명령으로 최신성 여부가 포함된 사용량 정보를 확인합니다." },
    ],
    progress: [
      { state: "done", title: "공개 배포", body: "Universal DMG와 GitHub Releases 배포 흐름 제공" },
      { state: "done", title: "서명된 자동 업데이트", body: "Sparkle 기반 업데이트와 무결성 확인" },
      { state: "done", title: "로컬 사용량 공유", body: "다른 앱과 대화를 위한 최신성 포함 JSON 및 명령 제공" },
      { state: "done", title: "통합 사용량 패널", body: "메뉴 패널과 항상 보기의 레이아웃·설정 통합 및 배경 불투명도 조절" },
      { state: "done", title: "집중된 3열 패널", body: "Codex·Claude·Gemini만 노출하고 퍼센트 굵기를 통일한 정밀 원형 링과 하단 조작을 3열에 맞게 재구성" },
      { state: "done", title: "Claude 인증 창 반복 방지", body: "요청 제한 뒤에도 인증 정보를 안전하게 재사용해 macOS 키체인 권한 창이 반복해서 나타나지 않도록 개선" },
      { state: "done", title: "CCMB 2.0.12 공개", body: "CCMB 전용 Claude 연결, 세 서비스의 독립 스마트 갱신, 정렬된 하단 조작부와 이름·말줄임표 없이 한 줄로 보이는 갱신 기록을 담은 Apple 공증 Universal DMG 공개" },
    ],
    screenshots: [
      { src: "/apps/ccmb/screens/ccmb-usage-menu.png", alt: "CCMB의 Codex·Claude·Gemini 사용량 메뉴", layout: "menu" },
      { src: "/apps/ccmb/screens/macos-menubar.png", alt: "macOS 메뉴 막대에 표시된 CCMB 사용량", layout: "wide" },
    ],
    github: ["https://github.com/armsone/CCMB"],
    privacy: [
      "현재 Mac 사용자의 Codex CLI·Antigravity CLI 로그인 세션을 이용하며 API 키를 앱에 포함하지 않습니다. Claude는 CCMB 전용 브라우저 연결을 사용합니다.",
      "Claude Code의 키체인 인증 정보는 읽지 않습니다. CCMB의 Claude refresh token은 CCMB 전용 macOS 키체인 항목에 보관하고 사용량 요청에 필요한 access token만 자동 갱신합니다.",
      "Grok 사용량 수집 기반과 로컬 공유 JSON 필드는 유지하지만 현재 화면과 공유 메뉴의 기본 요청문에서는 노출하지 않습니다. Grok CLI 기록을 읽을 때도 질문이나 응답 내용은 보관하거나 공개하지 않습니다.",
      "사용량 정보는 사용자의 Mac에서 표시되고, 앱 자체 분석이나 원격 측정 기능을 추가하지 않습니다.",
      "진단 로그의 문자열은 비공개로 처리하며 원시 요청과 응답 본문을 기록하지 않습니다.",
    ],
  },
  {
    slug: "btn",
    name: "BTN",
    english: "BTN",
    eyebrow: "BRING YOUR MAC BACK TO NORMAL",
    tagline: "개발 도구가 빌려 쓴 공간과 메모리를, 안전하게 돌려놓습니다.",
    summary: "AI·개발 작업 뒤 남은 시뮬레이터·작업 산출물과 유휴 개발 프로세스를 찾아 위험도와 이유를 설명하고, 안전한 파일은 자동으로 정리하거나 사용자가 고른 항목만 다시 확인한 뒤 처리하는 macOS 메뉴 막대 앱입니다.",
    theme: "blue",
    icon: "/apps/btn/icon.png",
    artwork: "cleanup",
    platforms: [
      {
        name: "macOS",
        status: "공개",
        detail: "2.0.2 (202608291620) · 내부 build 346580 · macOS 13+ · Universal · Apple 공증 완료",
        url: releaseDownloadPath("BTN"),
        downloadLabel: "Mac용 DMG 바로 받기",
        checksum: "7150296496f7a573f9ac0b1bceed82388b8f680e05fe46ad4fa7ef1d5bcaf99e",
      },
    ],
    features: [
      { title: "메모리 압박 해결 동선", body: "메모리 압박 경고에서 실행 중인 시뮬레이터를 기기 데이터를 유지한 채 종료하거나 활동 모니터로 일반 앱을 바로 확인합니다." },
      { title: "안전한 파일 자동 정리", body: "저위험이며 휴지통에서 복원 가능한 오래된 DerivedData와 XCTest 데이터만 자동으로 정리합니다." },
      { title: "시뮬레이터 잔여물 진단", body: "사용할 수 없어진 시뮬레이터와 명시적으로 확인된 XCTest 복제 기기를 찾아 디스크 사용량과 함께 보여줍니다." },
      { title: "시뮬레이터 데이터 초기화", body: "종료된 정상 시뮬레이터 데이터가 512 MiB 이상이면 기기는 남기고 앱·콘텐츠 데이터만 초기화할 수 있습니다." },
      { title: "DerivedData 안전 정리", body: "실행 중인 Xcode 빌드·테스트가 없을 때만 오래된 개별 DerivedData 폴더를 후보로 제안합니다." },
      { title: "유휴 프로세스 메모리 회수", body: "엄격한 유휴 조건을 충족한 Gradle·Kotlin 데몬, 테스트 러너와 브라우저 자동화만 종료 후보로 제안하며 로컬 개발 서버는 관찰만 합니다." },
      { title: "기본은 선택 안 함", body: "발견한 항목을 자동 선택하거나 즉시 지우지 않습니다. 사용자가 이유와 경로를 보고 직접 고릅니다." },
      { title: "실행 직전 다시 확인", body: "파일 식별 정보와 시뮬레이터 상태, 프로세스의 소유자·PID·명령·시작 시각을 조치 직전에 다시 검증해 바뀐 대상은 건너뜁니다." },
      { title: "파일은 우선 휴지통으로", body: "DerivedData와 XCTest 산출물은 복구할 수 있도록 휴지통으로 이동합니다. 시뮬레이터 삭제는 되돌릴 수 없음을 별도로 경고합니다." },
      { title: "로컬에서만 작동", body: "진단과 정리 판단은 Mac 안에서 규칙으로 수행하며 원격 분석이나 사용자 파일 업로드를 하지 않습니다." },
    ],
    guide: [
      { title: "DMG로 설치", body: "공식 DMG를 열고 BTN을 응용 프로그램 폴더로 옮긴 뒤 실행합니다." },
      { title: "메모리 압박 낮추기", body: "경고가 보이면 해결할 항목 찾기로 실행 중인 시뮬레이터를 기기 데이터를 유지한 채 종료하거나 활동 모니터를 엽니다." },
      { title: "남은 자원 찾기", body: "메뉴 막대에서 자세히 보기를 열고 정리 후보 찾기를 눌러 파일·시뮬레이터와 유휴 개발 프로세스를 확인합니다." },
      { title: "이유와 위험도 확인", body: "디스크 예상 확보량과 메모리 예상 회수량, 감지 이유와 위험도를 구분해 확인합니다." },
      { title: "정리할 항목 선택", body: "정리할 항목만 직접 체크하고 안전하게 해결을 누릅니다. 기본 상태에서는 아무 항목도 선택되지 않습니다." },
      { title: "최종 확인 후 실행", body: "확인 화면에서 되돌릴 수 없는 조치를 다시 확인한 뒤 실행하거나 취소합니다." },
    ],
    progress: [
      { state: "done", title: "디스크·시뮬레이터 진단", body: "사용 불가 시뮬레이터, XCTest 복제 기기와 오래된 DerivedData 후보 탐지" },
      { state: "done", title: "선택형 안전 정리", body: "실행 직전 재검증, 휴지통 이동과 개별 시뮬레이터 삭제 흐름 구현" },
      { state: "done", title: "메모리 원상복구", body: "유휴 개발 프로세스의 실행 직전 재검증과 정확한 PID별 정상 종료(SIGTERM) 구현" },
      { state: "done", title: "메모리 압박 해결", body: "데이터를 유지하는 실행 중 시뮬레이터 종료와 활동 모니터 연결 구현" },
      { state: "done", title: "BTN 2.0.0 공개", body: "build 202608230737의 Apple 공증 Universal DMG와 자동 업데이트를 공개" },
      { state: "done", title: "BTN 2.0.1 공개", body: "build 202608251555에서 닫힌 상세 창을 다시 실행할 때 즉시 복구하고 업데이트 자동 다운로드 설정을 추가" },
      { state: "done", title: "BTN 2.0.2 공개", body: "build 202608291620에서 메뉴의 중복된 자동 다운로드 스위치와 상태 문구를 덜어내고, 서명된 자동 업데이트는 그대로 유지한 Apple 공증 Universal DMG 공개" },
      { state: "next", title: "작업 세션 연동", body: "Codex·Claude·Gemini 작업별로 생성된 자원을 더 정밀하게 구분하는 추적 기능 준비" },
    ],
    screenshots: [
      { src: "/apps/btn/screens/overview.png", alt: "BTN이 메모리 압박 경고와 안전한 해결 동선을 보여주는 실제 화면", layout: "menu" },
    ],
    github: ["https://github.com/armsone/BTN"],
    privacy: [
      "프로세스, 시뮬레이터와 개발 산출물 상태는 진단을 위해 Mac 안에서만 확인합니다.",
      "선택한 파일은 우선 macOS 휴지통으로 이동하며, 시뮬레이터 데이터 초기화·삭제처럼 복구할 수 없는 조치는 실행 전에 별도로 알립니다. 실행 중 시뮬레이터 종료는 기기 데이터를 유지합니다.",
      "앱 자체 분석, 광고 추적, 원격 측정과 사용자 파일 업로드 기능을 포함하지 않습니다.",
    ],
  },
  {
    slug: "trackpadguard",
    name: "트랙패드가드",
    english: "TrackpadGuard",
    eyebrow: "TYPE WITHOUT THE CURSOR JUMP",
    tagline: "타이핑할 때는 잠그고, 원하는 곳을 터치해 다시 켜세요.",
    summary: "키 입력 중 트랙패드의 커서 이동·클릭·스크롤을 막고, 마지막 입력 1초 후 또는 지정한 물리적 영역을 터치하면 자동으로 해제하는 macOS 메뉴 막대 앱입니다.",
    theme: "blue",
    icon: "/apps/trackpadguard/icon.png",
    artwork: "trackpad",
    platforms: [
      { name: "macOS", status: "공개", detail: "2.0.3 (202608291556) · 내부 build 346556 · macOS 13+ · Universal · Apple 공증 완료", url: releaseDownloadPath("TrackpadGuard"), downloadLabel: "Mac용 DMG 바로 받기", checksum: "818ef1564f02ab9a898c0fdc25e11bb910e3ffda34457f57b99ba7c25dea0f86" },
    ],
    features: [
      { title: "키 입력과 동시에 잠금", body: "문자를 입력하기 시작하면 트랙패드의 커서 이동, 클릭과 스크롤을 바로 차단합니다." },
      { title: "1초 후 자동 해제", body: "마지막 키 입력 뒤 1초 동안 추가 입력이 없으면 트랙패드 잠금을 자동으로 해제합니다." },
      { title: "터치로 자연스럽게 해제", body: "기본 사다리꼴 또는 사용자가 정한 영역을 새로 터치하면 트랙패드가 즉시 다시 작동합니다." },
      { title: "눈으로 편집하는 영역", body: "설정 화면에서 네 꼭짓점을 직접 드래그해 손과 사용 습관에 맞는 해제 영역을 만듭니다." },
      { title: "실패 안전 설계", body: "멀티터치 좌표를 읽지 못하면 잠금을 시작하지 않으며, 긴급 단축키로 언제든 즉시 해제할 수 있습니다." },
      { title: "서명된 자동 업데이트", body: "Sparkle과 GitHub Releases를 통해 서명된 새 버전을 확인하고 설치합니다." },
      { title: "눈에 보이는 잠금 상태", body: "가드가 적용되면 메뉴 막대 아이콘이 빨간색으로 바뀌고 해제되면 원래 색으로 돌아옵니다." },
      { title: "높은 부하도 스스로 복구", body: "CPU·메모리 사용량이나 앱 응답 지연이 계속되면 보호 기능을 먼저 다시 시작하고, 같은 문제가 반복될 때만 앱을 안전하게 재시작합니다. 설정에서 자동 복구를 끌 수도 있습니다." },
    ],
    guide: [
      { title: "앱 설치", body: "공식 GitHub Release의 DMG를 열고 TrackpadGuard를 Applications 폴더로 옮깁니다." },
      { title: "손쉬운 사용 권한", body: "시스템 설정의 개인정보 보호 및 보안에서 TrackpadGuard의 손쉬운 사용 권한을 허용합니다." },
      { title: "작동 영역 조절", body: "설정의 작동 영역 탭에서 초록색 꼭짓점을 드래그합니다. 기본값은 상단 1/3을 제거한 사다리꼴입니다." },
      { title: "타이핑과 자동 해제", body: "키를 누르면 아이콘이 빨간색으로 바뀌며 트랙패드가 잠깁니다. 마지막 입력 1초 후에는 자동으로 다시 작동합니다." },
      { title: "영역 터치로 바로 해제", body: "1초를 기다리지 않고 설정한 초록색 영역을 새로 터치해 즉시 잠금을 해제할 수도 있습니다." },
      { title: "다른 포인터 장치", body: "마우스·트랙볼·펜 태블릿을 이동하거나 클릭·스크롤하면 잠금이 즉시 해제됩니다." },
      { title: "긴급 해제", body: "영역 인식에 문제가 생기면 Control-Option-Command-Escape를 눌러 즉시 잠금을 해제합니다." },
    ],
    progress: [
      { state: "done", title: "입력 잠금과 터치 해제", body: "Quartz 이벤트 필터와 물리적 멀티터치 좌표 기반 해제 흐름 구현" },
      { state: "done", title: "자동 해제와 상태 표시", body: "마지막 키 입력 1초 후 자동 해제와 잠금 중 빨간 메뉴 막대 아이콘 구현" },
      { state: "done", title: "사다리꼴 기본 영역과 편집", body: "상단 1/3을 제거한 기본값, 네 꼭짓점 드래그와 설정 저장 구현" },
      { state: "done", title: "Universal 배포 기반", body: "Apple Silicon·Intel 앱 번들, DMG, Sparkle와 GitHub Release 관리 흐름 구성" },
      { state: "done", title: "2.0.2 서명·공증 배포", body: "build 202608261902의 Developer ID 서명·Apple 공증 DMG와 자동 업데이트를 공개하고 장시간 실행 뒤 Mac의 시스템 키보드 입력이 느려지는 현상을 막았습니다." },
      { state: "done", title: "2.0.3 높은 부하 자동 복구 공개", body: "build 202608291556의 Developer ID 서명·Apple 공증 DMG를 공개했습니다. 지속되는 CPU·메모리 부하와 응답 지연을 단계적으로 감지하고 보호 기능을 자동 복구합니다." },
      { state: "next", title: "macOS 호환성 관리", body: "macOS 업데이트마다 비공개 멀티터치 프레임워크 호환성을 확인" },
    ],
    screenshots: [
      { src: "/apps/trackpadguard/screens/usage-square.png", alt: "TrackpadGuard가 키보드 입력 중 트랙패드를 잠그고 초록 영역 터치로 해제되는 과정을 설명하는 그림", layout: "square" },
    ],
    github: ["https://github.com/armsone/TrackpadGuard"],
    privacy: [
      "키 입력 내용은 저장하거나 전송하지 않고 키가 눌렸다는 상태만 잠금 시작에 사용합니다.",
      "트랙패드 접촉 좌표는 잠금 해제 영역 판정에만 사용하며 앱 밖으로 보내거나 기록하지 않습니다.",
      "앱 자체 분석, 광고 추적과 원격 측정 기능을 포함하지 않습니다.",
    ],
  },
  {
    slug: "htoms-brief",
    name: "HtOMS 브리프",
    english: "HtOMS Brief",
    eyebrow: "TODAY'S OMS, AT A GLANCE",
    tagline: "오늘의 매출과 서버 상태를, 한 페이지에서.",
    summary: "HtOMS의 실제 OMS 데이터를 읽어 오늘·이번 달 매출, 시간대·월간 추이, 출고 현황과 외부 서버 상태를 한 화면에 보여주는 iPhone·iPad·Android용 읽기 전용 브리프 앱입니다.",
    theme: "blue",
    icon: "/apps/htoms-brief/icon.png",
    artwork: "htoms",
    platforms: [
      { name: "iOS · iPadOS", status: "TestFlight", detail: "2.0.0 (202608291628) · iOS·iPadOS 17+", availabilityNote: "회사 내부 테스트 전용 · 내부 테스터 9명 유지 · 공개 링크 없음" },
      {
        name: "Android · Google TV",
        status: "공개",
        detail: "2.1.1 · 빌드 202608291542 · 내부 코드 346542 · Android 8.0+",
        url: releaseDownloadPath("HtOMS-BK"),
        downloadLabel: "Android용 APK 다운로드",
        checksum: "66ebee56a5724be93798dd7de7dbd6a80e2139d4cf4bfcc19ae6bbf45806c54d",
        availabilityNote: "서명 APK 재다운로드·무결성 검증 완료 · SM-F968N 데이터 유지 교체 설치·실행 확인",
      },
    ],
    features: [
      { title: "실제 OMS 매출 데이터", body: "로그인한 계정으로 오늘·이번 달 매출과 시간대·월간 추이를 실제 API에서 읽어 표시합니다." },
      { title: "한 페이지 브리프", body: "오늘의 매출, 위치별 현황, 외부 서버 상태와 출고 현황을 세로 한 화면 흐름으로 확인합니다." },
      { title: "화면 안전 영역", body: "상태 표시줄과 내비게이션 영역을 피해 콘텐츠를 배치해 최신 Android의 edge-to-edge 화면에서도 숫자와 버튼이 가려지지 않습니다." },
      { title: "10분 자동 갱신", body: "다음 갱신까지 남은 시간을 역타이머로 보여주고 0초가 되면 자동으로 다시 가져옵니다. 화면을 누르면 즉시 갱신합니다." },
      { title: "외부 서버 이상 표시", body: "장항·인천·삼송·초월 서버는 평소 회색, 문제가 생기면 빨간색으로 바뀝니다." },
      { title: "안전한 로그인", body: "로그인 세션은 Apple Keychain 또는 Android Keystore로 보호하며 앱 화면과 일반 저장 데이터에 원문을 노출하지 않습니다." },
      { title: "홈 화면 위젯", body: "앱에서 갱신한 핵심 브리프를 iPhone·iPad와 Android 홈 화면에서도 빠르게 확인합니다." },
    ],
    guide: [
      { title: "로그인", body: "회사 OMS 계정으로 로그인하면 실제 조회 권한에 따라 브리프 데이터를 가져옵니다." },
      { title: "한 화면에서 확인", body: "오늘의 매출 아래 위치별 현황과 서버 상태를 보고, 이어서 매출 추이와 출고 현황을 확인합니다." },
      { title: "즉시 갱신", body: "다음 자동 갱신까지 남은 시간이 표시되며, 기다리지 않고 화면을 눌러 바로 새로 가져올 수 있습니다." },
    ],
    progress: [
      { state: "done", title: "실제 OMS 연동", body: "로그인, 매출·출고·위치·외부 서버 데이터 조회 구현" },
      { state: "done", title: "iOS·iPadOS 2.0.0 업로드", body: "build 202608230737 TestFlight 처리 완료" },
      { state: "done", title: "한 페이지 대시보드", body: "분리됐던 정보를 한 화면의 읽기 흐름으로 통합" },
      { state: "done", title: "자동·수동 갱신", body: "10분 역타이머와 터치 즉시 갱신 구현" },
      { state: "done", title: "iPhone·iPad 검증", body: "공통 빌드와 실제 iPhone 설치·실행 검증" },
      { state: "done", title: "iOS 내부 빌드 갱신", body: "build 202608291628을 회사 내부 TestFlight 그룹에 제공하고 외부 공개 링크는 비활성으로 유지" },
      { state: "done", title: "Android 대응 앱 구현", body: "2.0.0 휴대전화·태블릿·Google TV용 Compose 앱과 Glance 위젯의 단위 테스트·공개용 QA 빌드·린트 검증" },
      { state: "done", title: "Android 2.1.1 공개", body: "edge-to-edge 안전 영역을 보강한 제품 2.1.1 · 빌드 202608291542 · 내부 코드 346542의 서명 APK와 SHA-256 체크섬을 GitHub Releases에 공개" },
      { state: "next", title: "Android 화면 매치업", body: "태블릿과 Google TV를 포함한 대표 기기 화면을 iPhone·iPad 기준과 비교해 세부 배치를 조정" },
    ],
    screenshots: [
      { src: "/apps/htoms-brief/screens/login.png", alt: "HtOMS 브리프의 사내 계정 로그인과 Keychain 안내 화면" },
    ],
    github: ["https://github.com/armsone/HtOMS-BK"],
    privacy: [
      "OMS 로그인 세션은 Apple Keychain 또는 Android Keystore로 보호하며 홈페이지나 앱의 일반 설정에 원문으로 저장하지 않습니다.",
      "앱은 업무 현황 확인을 위한 읽기 전용 API 요청만 수행하며 주문을 생성하거나 변경하지 않습니다.",
      "화면에는 매출·출고 집계와 서버 상태를 표시하고 개별 주문의 개인정보를 별도로 보관하지 않습니다.",
    ],
  },
  {
    slug: "intosharp",
    name: "인투샾",
    english: "intoSharp",
    eyebrow: "OPEN THE WEB BY NAME",
    tagline: "주소 대신 이름으로 여는 첫 화면.",
    summary: "검색과 자주 가는 사이트를 한 화면에 모으고, 사이트 이름과 검색어만으로 빠르게 이동하는 개인화 웹 시작 페이지입니다.",
    theme: "blue",
    icon: "/apps/intosharp/icon.png",
    artwork: "search",
    platforms: [
      { name: "Web", status: "공개", detail: "PC · 모바일 반응형", url: "https://intosharp.com/", downloadLabel: "인투샾 열기" },
    ],
    features: [
      { title: "이름으로 바로 이동", body: "주소를 외울 필요 없이 등록된 사이트 이름을 입력하면 해당 페이지를 바로 엽니다." },
      { title: "검색까지 한 줄에서", body: "네이버·Google·YouTube·지도·쇼핑을 고르고 검색어를 입력해 원하는 곳에서 바로 찾습니다." },
      { title: "자주 가는 곳을 한눈에", body: "일, 이야기마당, 볼거리, 연장 등 쓰임에 따라 나눈 이음말을 한 화면에서 확인합니다." },
      { title: "내 시작 화면으로", body: "검색 서비스와 밝고 어두운 화면을 기기에 기억해 다음 방문에도 이어서 사용합니다." },
    ],
    guide: [
      { title: "사이트 열기", body: "검색줄에 등록된 사이트 이름을 입력하고 Enter를 누르면 바로 이동합니다." },
      { title: "원하는 곳에서 검색", body: "검색 서비스를 선택한 뒤 검색어를 입력하거나 ‘네이버 우리집’처럼 이름과 검색어를 함께 씁니다." },
      { title: "이음말 둘러보기", body: "화면 아래의 분야별 카드에서 자주 쓰는 사이트를 찾아 엽니다." },
      { title: "첫 화면으로 사용", body: "브라우저의 시작 페이지나 홈 화면 바로가기에 인투샾을 등록해 사용합니다." },
    ],
    progress: [
      { state: "done", title: "공개 웹 서비스", body: "intosharp.com에서 PC와 모바일로 바로 이용 가능" },
      { state: "done", title: "통합 이동과 검색", body: "사이트 이름 이동과 서비스별 검색 문법 구현" },
      { state: "active", title: "개인화 관리", body: "이음말과 화면 구성을 더 편하게 관리하는 흐름을 다듬는 중" },
      { state: "next", title: "이음말 확장", body: "개인 시작 페이지에서 검증한 이름 기반 연결 경험을 확장" },
    ],
    github: [],
    privacy: [
      "선택한 검색 서비스와 화면 테마는 다음 방문을 위해 브라우저에 저장될 수 있습니다.",
      "검색을 실행하면 입력한 검색어가 사용자가 선택한 외부 검색 서비스로 전달되며 해당 서비스의 개인정보처리방침이 적용됩니다.",
      "관리 기능의 인증정보 원문은 공개 페이지 데이터에 저장하지 않습니다.",
    ],
  },
  {
    slug: "airchurch",
    name: "에어처치",
    english: "airChurch",
    eyebrow: "FAITH MEETS GOOD WILL",
    tagline: "좋은 말씀과 선한 마음이 만나는 곳.",
    summary: "검증한 교회의 설교와 찬양을 발견하고, 우리 교회를 응원하며, 가진 달란트로 이웃의 필요를 잇는 크리스천 웹 포털입니다.",
    theme: "coral",
    icon: "/apps/airchurch/icon.png",
    artwork: "church",
    platforms: [
      { name: "Web", status: "공개", detail: "PC · 모바일 반응형", url: "https://airchurch.net/", downloadLabel: "에어처치 열기" },
    ],
    features: [
      { title: "오늘의 말씀과 찬양", body: "교단 소속과 공식 채널을 확인한 교회의 최신 설교와 찬양을 한곳에서 발견합니다." },
      { title: "경쟁보다 발견", body: "목회자의 서열을 만들기보다 작은 교회와 지역의 꾸준한 사역이 발견되도록 보여줍니다." },
      { title: "착한나눔", body: "시간, 경험, 공간, 기술과 기도를 필요한 교회와 이웃에게 연결합니다." },
      { title: "서로를 지키는 광장", body: "개인정보를 최소화한 별칭으로 이야기를 나누고 운영 원칙에 따라 첫 글을 검토합니다." },
      { title: "분명한 검증 기준", body: "교단·노회·공식 홈페이지와 영상 채널을 교차 확인하고 신고·재검토·이의제기 절차를 둡니다." },
    ],
    guide: [
      { title: "말씀 찾기", body: "교회명, 목사님 또는 지역을 검색하고 공식 채널의 설교를 확인합니다." },
      { title: "찬양 듣기", body: "여러 교회의 최신 찬양을 둘러보고 공식 YouTube 영상으로 이어서 듣습니다." },
      { title: "교회 응원하기", body: "건강한 발견에 도움이 되도록 마음을 전하고, 지역별 교회를 살펴봅니다." },
      { title: "달란트 나누기", body: "도울 수 있는 일과 활동 지역을 남기면 공개 전 확인을 거쳐 실제 필요와 연결합니다." },
      { title: "광장 참여하기", body: "공동체 원칙을 확인하고 별칭으로 신앙과 삶의 이야기를 나눕니다." },
    ],
    progress: [
      { state: "done", title: "공개 웹 포털", body: "airchurch.net에서 PC와 모바일로 이용 가능" },
      { state: "done", title: "설교·찬양 발견", body: "공식 채널 기반 콘텐츠 검색과 지역 필터 구현" },
      { state: "active", title: "검증과 운영 안정화", body: "교회 정보 검토, 콘텐츠 동기화와 운영자 관리 흐름을 개선 중" },
      { state: "active", title: "착한나눔과 광장", body: "접수·검토·공개 절차와 안전 장치를 실제 운영에 맞춰 다듬는 중" },
    ],
    github: [],
    privacy: [
      "공개 콘텐츠를 둘러보는 데 회원 가입이나 개인 연락처 입력을 요구하지 않습니다.",
      "달란트 나눔과 광장에 사용자가 직접 입력한 내용은 접수와 공개 전 검토를 위해 처리합니다.",
      "외부 설교와 찬양을 열면 YouTube 등 해당 서비스의 개인정보처리방침이 적용됩니다.",
    ],
  },
  {
    slug: "button",
    name: "버튼",
    english: "Button",
    eyebrow: "ONE TAP, YOUR FAMILY HEARS YOU",
    tagline: "가족을 부르는 가장 간단한 버튼.",
    summary: "가족 기기를 QR로 여러 공간에 묶고 톡톡·띵동·음성과 긴급 사이렌을 보내는 iPhone·Android 가족 호출 앱입니다. 아이도 한눈에 구분하도록 밝고 따뜻한 화면을 쓰며, 개인 NAS가 원거리 호출을 중계합니다.",
    theme: "coral",
    icon: "/apps/button/icon.png",
    artwork: "phones",
    platforms: [
      { name: "iPhone", status: "TestFlight", detail: "2.0.0 (202608252204) · iOS 17+", availabilityNote: "Public Beta 승인 · 공개 테스트 참여 가능" },
      {
        name: "Android",
        status: "공개",
        detail: "2.0.2 · 빌드 202608291453 · 내부 코드 346493 · Android 8.0+",
        url: releaseDownloadPath("button-Android"),
        downloadLabel: "Android APK 바로 받기",
        checksum: "4b9cc233fc527370d103d67c2c81e6c752222b97aa1d678e8cfe2bcd0b847239",
        availabilityNote: "기존 공개판과 같은 전용 서명 · SM-T500 데이터 유지 교체 설치·실행 확인",
      },
    ],
    features: [
      { title: "톡톡에서 사이렌까지", body: "톡톡은 탭하면 소리 없이 전해지고, 5초간 누르면 보낸 기기는 조용한 채 상대 기기에 강력한 사이렌을 보냅니다." },
      { title: "녹음하고 확인해서 보내기", body: "음성을 녹음한 뒤 보내기 또는 취소를 한 번 더 고릅니다. 받는 사람은 앱에서 바로 듣고 최근 기록에서 다시 들을 수 있습니다." },
      { title: "한 명·여러 명 또는 모두에게", body: "원거리에 있는 가족까지 받을 사람 목록에 표시합니다. 한 명 이상을 골라 보내거나 선택 없이 모두에게 보냅니다." },
      { title: "앱을 보는 동안 화면 유지", body: "버튼 앱이 앞에 열려 있는 동안에는 화면이 꺼지지 않아 가족 호출 버튼을 바로 누를 수 있습니다." },
      { title: "여러 가족 공간", body: "가족별로 별도 공간을 만들고 참여한 공간 사이를 전환할 수 있어 다른 가족에게도 같은 앱을 소개해 사용할 수 있습니다." },
      { title: "잠금화면 원격 수신", body: "iPhone은 APNs, Android는 FCM을 사용해 앱이 화면에 없거나 잠겨 있을 때도 대상 호출을 안전하게 전달합니다." },
      { title: "근거리 연결과 원거리 중계", body: "가까운 기기는 직접 연결하고, 개인 Synology NAS 중계 서버가 iPhone과 Android의 원거리 호출을 함께 이어줍니다." },
      { title: "20개 기록과 확인 인원", body: "최근 기록은 20개만 남기고 오래된 항목부터 정리합니다. 보낸 기록 오른쪽에는 아직 확인하지 않은 사람 수가 표시되고 모두 확인하면 사라집니다." },
      { title: "자녀의 연속 호출 방지", body: "자녀가 호출한 뒤에는 10초 동안 남은 시간을 표시해 실수로 연속 전송하는 일을 막고, 부모는 제한 없이 바로 다시 보낼 수 있습니다." },
      { title: "부모와 자녀 모두 음성 전송", body: "부모와 자녀 모두 톡톡·띵동·음성을 보낼 수 있고, 자녀의 연속 호출만 10초 동안 제한합니다." },
    ],
    guide: [
      { title: "공간 만들기", body: "한 기기에서 가족 공간을 만들고 표시된 QR 코드를 가족 기기에서 스캔합니다. 다른 가족용 공간도 별도로 추가할 수 있습니다." },
      { title: "이름과 역할 정하기", body: "각 기기의 이름을 확인하고 부모 또는 자녀 역할을 선택합니다." },
      { title: "받을 사람 선택", body: "모두에게 보내려면 선택하지 않고, 따로 보내려면 가까이 있거나 원거리에 있는 가족 이름을 한 명 이상 누릅니다." },
      { title: "호출 보내기", body: "큰 정사각형 톡톡·띵동·음성 버튼 중 하나를 누릅니다. 톡톡을 5초간 누르면 사이렌을 보내고, 음성은 녹음을 마친 뒤 보내기를 한 번 더 확인합니다." },
      { title: "알림 권한 확인", body: "iPhone 또는 Android 설정에서 버튼 앱의 알림과 소리를 허용합니다. Android 설정에서 원격 알림을 켜면 FCM 등록 상태를 확인할 수 있습니다." },
    ],
    progress: [
      { state: "done", title: "여러 가족 공간과 연결", body: "QR 참여, 별도 공간 추가·전환, 근거리 연결과 원거리 가족 목록 구현" },
      { state: "done", title: "세 가지 호출과 확인", body: "큰 정사각형 톡톡·띵동·음성 버튼, 개별 전송, 20개 최근 기록과 미확인 인원 표시 구현" },
      { state: "done", title: "원거리 푸시 중계", body: "Synology NAS에서 APNs와 FCM을 함께 운영해 iPhone·Android 잠금·백그라운드 호출 지원" },
      { state: "done", title: "여러 사람 선택과 화면 유지", body: "한 명 이상을 골라 보내는 대상 전송과 앱이 앞에 있는 동안 화면 꺼짐 방지 구현" },
      { state: "done", title: "밝고 직관적인 가족 화면", body: "우리 공간을 먼저 보고 민트·노랑·로즈의 큰 버튼을 누르도록 밝고 따뜻한 BK 스타일 적용" },
      { state: "done", title: "iPhone 2.0.0 업로드", body: "build 202608230737 TestFlight 처리 완료" },
      { state: "done", title: "Android 2.0.1 공개", body: "제품 2.0.1 · 빌드 202608251400 · 내부 코드 340680의 기존 설치 호환 전용 서명 APK와 제품 버전 기준 자동 업데이트를 GitHub Releases에 공개" },
      { state: "done", title: "Android 2.0.2 여러 공간 안정화 공개", body: "공간을 바꿔도 진행 중인 전송 대상이 섞이지 않고 구성원·알림 상태를 정확히 새로고침하는 패치를 전용 서명 APK로 공개" },
      { state: "done", title: "NAS 여러 공간 중계 반영", body: "운영 서버를 최신 여러 공간 서버로 교체하고 원거리 가족 목록 경로까지 확인" },
      { state: "done", title: "Android 원격 수신", body: "FCM 등록·백그라운드 대상 검증·원본 띵동 소리·호출 기록까지 NAS 실전 전달 확인" },
    ],
    screenshots: [
      { src: "/apps/button/screens/android-voice_recording.png", alt: "버튼 Android 부모 홈에서 방 이름 아래 녹음 중 상태가 표시된 화면" },
      { src: "/apps/button/screens/android-siren_countdown.png", alt: "버튼 Android 부모 홈에서 방 이름 아래 사이렌까지 3초가 표시된 화면" },
      { src: "/apps/button/screens/android-parent-targeted.png", alt: "버튼 Android에서 한 가족 구성원을 선택한 부모 홈" },
      { src: "/apps/button/screens/android-parent-sent.png", alt: "버튼 Android에서 특정 가족에게 띵동 호출을 보낸 상태" },
      { src: "/apps/button/screens/android-child-ack.png", alt: "버튼 Android 자녀 홈의 호출 확인 활동" },
      { src: "/apps/button/screens/android-settings.png", alt: "버튼 Android 알림과 원격 호출 설정" },
    ],
    github: ["https://github.com/armsone/button", "https://github.com/armsone/button-Android"],
    privacy: [
      "가족 공간 식별자, 기기 이름과 역할은 호출 연결을 위해 기기와 사용자가 지정한 개인 중계 서버에서 처리합니다.",
      "iPhone APNs와 Android FCM 기기 토큰은 해당 가족 공간의 원거리 호출 전달에만 사용합니다.",
      "목소리 메시지는 사용자가 녹음을 선택한 경우에만 생성되며 호출 전달을 위해 가족 기기와 개인 중계 서버 사이에서 처리됩니다.",
      "앱은 광고 추적 기능을 포함하지 않으며 가족 공간 밖의 사용자에게 호출 데이터를 판매하거나 제공하지 않습니다.",
    ],
  },
  {
    slug: "starmanager",
    name: "스타메니저",
    english: "StarManager",
    eyebrow: "YOUR STORY, READY TO SHARE",
    tagline: "오늘의 이야기를, 내 목소리로 완성합니다.",
    summary: "사진만, 사진과 글, 글만으로 시작하면 Gemini·ChatGPT·Claude 또는 기기 AI가 내 목소리에 맞는 게시물 초안을 완성합니다. 미디어를 먼저 보며 한 화면에서 쓰고 다듬은 뒤 Instagram 등 원하는 앱으로 바로 이어가는 iPhone·iPad·Android 앱입니다.",
    theme: "violet",
    icon: "/apps/starmanager/icon.png",
    artwork: "phones",
    platforms: [
      { name: "iPhone · iPad", status: "TestFlight", detail: "2.5.1 · 빌드 202608291746 · iOS·iPadOS 18+", availabilityNote: "2.5.1 Public Beta 심사 대기 · 공개 링크 활성 · 승인된 이전 빌드 테스트 가능" },
      {
        name: "Android",
        status: "공개",
        detail: "2.5.1 · 빌드 202608291746 · 내부 코드 346666 · Android 8.0+",
        url: releaseDownloadPath("StarManager-Android"),
        downloadLabel: "Android APK 바로 받기",
        checksum: "c5231e91bb4ca8b3e1d230137a7f70649965fcb7f2b2e45cefbec29024212f91",
        availabilityNote: "휴대전화·태블릿·Google TV 지원 · Android 실기기 3대에서 데이터 유지 교체 설치·실행 확인",
      },
    ],
    features: [
      { title: "고른 사진을 모두 AI에", body: "사진 1~8장을 고른 순서대로 Gemini·ChatGPT·Claude에 전달합니다. 사진만 맡기거나 사진과 글을 함께 보내도 되고, 영상은 AI 첨부에서 제외됩니다." },
      { title: "화면을 가리지 않는 외부 AI", body: "ChatGPT·Gemini·Claude에 요청을 보낸 뒤에도 스튜디오 화면을 그대로 보며 전송 완료·대기 시간·오류 상태를 확인할 수 있습니다." },
      { title: "필요할 때만 브라우저 보기", body: "브라우저 보기는 기본적으로 꺼져 있습니다. 설정에서 켜면 생성 시작부터 공식 웹 화면을 볼 수 있고, 꺼져 있어도 로그인·보안 확인이 필요할 때는 자동으로 화면을 엽니다." },
      { title: "로그인 상태를 직접 관리", body: "설정에서 Gemini·ChatGPT·Claude의 로그인 상태를 다시 확인하고, 모두 로그아웃한 뒤 필요한 서비스에 다시 로그인할 수 있습니다." },
      { title: "결과를 안정적으로 가져오기", body: "외부 AI의 완성된 답변을 감지해 스타메니저 초안으로 바로 가져옵니다. 결과를 받거나 화면을 스크롤하면 입력 키보드는 다시 입력창을 누를 때까지 숨깁니다." },
      { title: "원하는 AI를 바로 선택", body: "Gemini·ChatGPT·Claude·기기 AI를 한 줄에서 고르고 각 AI의 만들기 버튼으로 곧바로 실행합니다." },
      { title: "접어 두는 글 스타일", body: "글자 수·이모지·분위기·스타일·말투·나잇대·줄넘김·내 글 반영은 필요할 때만 펼칩니다. 추가 요청은 같은 패널에서 직접 적습니다." },
      { title: "새 캔버스로 다시 시작", body: "하단의 새 캔버스로 현재 이야기와 결과, 미디어만 비우고 나의 취향과 프로필은 그대로 유지합니다." },
      { title: "미디어와 Instagram 공유", body: "사진·영상을 최대 8개까지 담고 순서를 정한 뒤, 문구 자동 복사와 공유 화면으로 Instagram 새 게시물 등 원하는 앱에 연결합니다. 카메라 사진은 사진 앱·갤러리에도 보관합니다." },
      { title: "사진 앱에서 바로 시작", body: "사진 앱의 공유 메뉴에서 사진을 최대 8장까지 StarManager로 보내면 공동 보관함을 거쳐 새 자동화 캔버스에 바로 채웁니다." },
      { title: "내가 켤 때만 자동화", body: "자동화는 처음에는 꺼져 있습니다. 설정에서 직접 켜면 앱을 열거나 15초 이상 쉬었다 돌아올 때 사진 선택부터 Gemini·ChatGPT·Claude 전달까지 이어집니다." },
      { title: "공유와 카메라는 언제나", body: "자동화를 꺼 둬도 사진 앱에서 바로 공유할 수 있고, 홈 화면의 StarManager 아이콘을 길게 눌러 카메라를 곧바로 열 수 있습니다." },
      { title: "인터스텔라 테마", body: "BK·클래식과 함께 은빛과 금빛이 도는 어두운 인터스텔라 화면과 전용 앱 아이콘을 선택할 수 있습니다." },
      { title: "취소와 붙여넣기 안내", body: "게시물 만들기에서 취소를 누르면 작성 중인 내용을 버릴지 확인할 수 있습니다. iPhone·iPad에서 붙여넣기가 막히면 설정 → 앱 → 스타메니저 → 다른 앱에서 붙여넣기를 허용으로 바꾸고, Android는 앱별 붙여넣기 권한을 따로 설정하지 않습니다." },
    ],
    guide: [
      { title: "미디어와 이야기 입력", body: "사진·영상 또는 카메라로 미디어를 먼저 고르고 이야기를 적습니다. 사진만, 사진과 글, 글만 모두 가능합니다." },
      { title: "사진 앱에서 보내기", body: "사진 앱에서 사진을 고르고 공유 → StarManager를 누르면 사진이 자동화 캔버스에 바로 들어옵니다." },
      { title: "AI로 초안 만들기", body: "Gemini·ChatGPT·Claude·기기 AI 중 하나를 고른 뒤 해당 만들기 버튼을 누릅니다. 선택한 사진은 순서대로 가볍게 정리해 전송하며 진행 상태는 스튜디오에서 확인합니다." },
      { title: "결과 가져오기", body: "외부 AI의 답변이 완성되면 스타메니저가 결과를 가져와 미리보기에 표시합니다. 로그인하지 않았다면 나의 취향 아래쪽 외부 AI 로그인 관리에서 먼저 로그인합니다." },
      { title: "키보드 숨기기", body: "입력 뒤 화면을 위아래로 스크롤하면 키보드가 바로 숨겨집니다. 다시 입력하려면 입력창을 누릅니다." },
      { title: "미디어 추가", body: "사진·영상 또는 카메라로 미디어를 추가하고 순서와 대표 항목, 미리보기 화면비를 정합니다." },
      { title: "공유", body: "초안과 미디어를 확인한 뒤 Instagram 새 게시물 등 원하는 앱으로 공유합니다. 카메라 사진은 사진 앱·갤러리에서도 확인할 수 있습니다." },
      { title: "브라우저 보기와 붙여넣기", body: "외부 AI 화면을 계속 보려면 나의 취향 → 외부 AI 로그인 관리에서 브라우저 보기를 켭니다. iPhone·iPad 붙여넣기가 막히면 설정 → 앱 → 스타메니저 → 다른 앱에서 붙여넣기 → 허용을 선택합니다." },
    ],
    progress: [
      { state: "done", title: "iPhone·iPad 원본 분석", body: "실제로 도달 가능한 만들기·내 설정 화면과 상태·문구·동작을 소스 기준으로 정리" },
      { state: "done", title: "Android 구현과 실기기 검증", body: "휴대전화·태블릿 반응형 화면, 생성·검증·미디어·설정 흐름 구현과 테스트 완료" },
      { state: "done", title: "Android 2.5.1 공개", body: "제품 2.5.1 · 빌드 202608291746 · 내부 코드 346666의 자동화·공유·카메라 흐름을 담은 APK를 GitHub Releases에 공개하고 Android 실기기 3대에서 데이터 유지 교체 설치·실행 검증" },
      { state: "done", title: "iPhone·iPad 2.5.1 설치·업로드", body: "2.5.1 (202608291746)을 사용 가능한 iPhone 2대에 데이터 유지 교체 설치하고 App Store Connect 업로드와 기존 내부 테스트 9명 연결을 확인" },
      { state: "active", title: "iOS·iPadOS 2.5.1 Public Beta 심사", body: "기본 꺼짐 자동화·공유 확장·카메라 퀵 액션·인터스텔라 테마를 담은 build 202608291746을 Public Beta 그룹에 연결하고 Beta App Review 대기 중이며 기존 공개 테스트 링크는 유지" },
      { state: "next", title: "게시 흐름 다듬기", body: "실제 공유 앱별 게시 결과와 사용자 피드백을 바탕으로 다음 개선 항목을 정리" },
    ],
    screenshots: [
      { src: "/apps/starmanager/screens/ios-composer.png", alt: "스타메니저 iPhone 스튜디오의 AI 선택과 새 캔버스 화면" },
      { src: "/apps/starmanager/screens/android-composer.png", alt: "스타매니저 Android 만들기 화면" },
      { src: "/apps/starmanager/screens/android-result.png", alt: "스타매니저 Android 게시물 생성 결과" },
      { src: "/apps/starmanager/screens/android-settings.png", alt: "스타매니저 Android 내 설정 화면" },
      { src: "/apps/starmanager/screens/android-ai-login.png", alt: "스타매니저 Android 앱 안에서 연 ChatGPT 공식 로그인 화면" },
      { src: "/apps/starmanager/screens/ios-style-settings.png", alt: "스타메니저 iPhone에서 펼친 글 스타일 설정" },
      { src: "/apps/starmanager/screens/android-style-settings.png", alt: "스타메니저 Android에서 펼친 글 스타일 설정" },
    ],
    github: [
      "https://github.com/armsone/StarManager",
      "https://github.com/armsone/StarManager-Android",
    ],
    privacy: [
      "프로필, 프리셋과 작성 설정은 사용자의 기기 안에 저장합니다.",
      "Apple AI를 사용할 수 있는 기기에서는 글 생성이 기기 안에서 처리됩니다.",
      "ChatGPT·Gemini·Claude를 선택하면 앱 안의 각 서비스 공식 웹페이지에 프롬프트를 전달하며 각 서비스의 개인정보처리방침이 적용됩니다.",
      "외부 AI 로그인 정보는 스타메니저가 직접 보거나 저장하지 않으며, 각 서비스의 웹 로그인 세션은 이 기기의 앱 전용 웹 데이터에 유지됩니다.",
      "외부 AI를 실행하면 사용자가 선택한 사진만 순서대로 해당 서비스에 전달하며, 영상은 AI에 보내지 않습니다.",
      "사용자가 고른 사진과 영상은 미리보기와 공유를 위해 앱 전용 임시 공간에서 처리합니다.",
    ],
    matchup: {
      metrics: [
        { value: "02", label: "도달 가능한 탭" },
        { value: "06", label: "글쓰기 스타일" },
        { value: "08", label: "미디어 최대 개수" },
      ],
      scope: [
        "만들기와 내 설정의 화면 구조·옵션·상태 흐름을 iOS 소스 기준으로 구현",
        "브랜드 색상과 AI 로고 원본, 프로필 마이그레이션과 글자 수 검증 규칙을 동일하게 적용",
        "휴대전화 세로 화면과 600dp 이상 태블릿의 2열 레이아웃을 각각 제공",
      ],
      note: "접힌 첫 화면과 펼친 글 스타일 설정의 iPhone·Android 캡처를 짝지어 확인했습니다. 새 다중 사진 경로는 Android 실기기에서 동작을 확인했으며 혼합 미디어·오류 복구·메모리 수명주기의 추가 회귀 검증은 계속 진행합니다.",
    },
  },
  {
    slug: "minecraft-server",
    name: "NasOS",
    english: "NasOS · Minecraft Server",
    eyebrow: "A PRIVATE WORLD FOR THE FAMILY",
    tagline: "아이들은 함께 짓고, 부모는 안심합니다.",
    summary: "NasOS는 실제로 사용하는 NAS 서버 설정을 설치 가능한 결과물로 관리합니다. 첫 공개 구성은 자녀와 함께 쓰는 Minecraft Bedrock 사설 서버용 Docker 설정과 부모용 운영 안내서이며, 실제 소규모 서버로 계속 사용 중입니다.",
    theme: "blue",
    icon: "/apps/minecraft-server/icon.png",
    artwork: "server",
    platforms: [
      {
        name: "NasOS · Synology NAS",
        status: "공개",
        detail: "0.1.0 · Container Manager · Docker Compose · Bedrock Edition · 실제 운영 확인",
        url: "https://github.com/armsone/NasOS/releases/tag/v0.1.0",
        downloadLabel: "NasOS 서버 설정 받기",
        availabilityNote: "개인정보를 제거한 서버 설정과 운영 안내서 공개 완료",
      },
    ],
    features: [
      { title: "명령어 없이 설치", body: "Docker 명령어나 SSH를 몰라도 DSM의 Container Manager와 File Station 화면만 따라가며 서버를 준비할 수 있습니다." },
      { title: "월드는 NAS에 안전하게", body: "월드와 설정을 컨테이너 밖의 전용 데이터 폴더에 보관해 컨테이너를 업데이트해도 플레이 기록을 이어갑니다." },
      { title: "집 안에서 먼저 시작", body: "처음에는 같은 Wi-Fi 안에서만 접속해 정상 동작을 확인하고, 자녀 기기에는 NAS 내부 주소와 Bedrock 포트만 등록합니다." },
      { title: "외부 접속은 더 조심스럽게", body: "외부 접속이 필요하면 허용 목록을 먼저 켜고, 관리 포트를 여는 대신 Tailscale 같은 사설 메시 VPN을 우선합니다." },
      { title: "작게 시작하는 안정 설정", body: "소규모 인원에 맞춘 메모리와 시야 거리, 온라인 계정 인증, 자동 재시작 설정으로 NAS의 다른 작업과 함께 운영합니다." },
      { title: "업데이트 전에는 백업", body: "월드 데이터 폴더를 Snapshot Replication이나 Hyper Backup으로 보관한 뒤 서버 이미지를 안전하게 갱신합니다." },
    ],
    guide: [
      { title: "준비물 확인", body: "Container Manager를 지원하는 Synology NAS, Minecraft Bedrock 앱과 계정, 같은 내부 네트워크를 준비합니다." },
      { title: "데이터 폴더 만들기", body: "File Station에서 월드가 계속 보존될 전용 폴더를 만들고 실제 경로는 외부에 공개하지 않습니다." },
      { title: "설정 파일 준비", body: ".env.example을 .env로 복사해 데이터 경로와 서버 이름을 정하고, Minecraft EULA에 동의한 경우에만 EULA 값을 활성화합니다." },
      { title: "Container Manager에서 시작", body: "docker-compose.yml과 .env가 있는 폴더를 프로젝트로 선택해 실행하고 로그의 Server started. 메시지를 확인합니다." },
      { title: "자녀 기기 연결", body: "같은 Wi-Fi에서 Minecraft 서버 추가를 열고 NAS 내부 주소와 UDP 19132를 입력합니다." },
      { title: "백업과 안전 설정", body: "외부 접속 전 허용 목록을 켜고 사설 VPN을 우선하며, 업데이트 전에는 데이터 폴더를 백업합니다." },
    ],
    progress: [
      { state: "done", title: "Synology NAS 설치", body: "Container Manager의 Docker 프로젝트로 Bedrock 서버 구성 완료" },
      { state: "done", title: "가족 사용 검증", body: "소규모 사설 서버가 실제로 실행되고 Bedrock 기기에서 계속 사용 중" },
      { state: "done", title: "개인정보 제거", body: "NAS 모델·버전, 주소, 경로, 서버 이름과 플레이어 식별정보를 공개 문서에서 제거" },
      { state: "done", title: "NasOS 0.1.0 공개", body: "개인정보를 제거한 서버 설정과 운영 안내서를 독립 GitHub 저장소와 릴리스로 공개" },
    ],
    github: ["https://github.com/armsone/NasOS"],
    privacy: [
      "실제 서버 주소, 데이터 경로, 서버 이름, 게이머태그와 XUID는 공개 문서와 홈페이지에 싣지 않습니다.",
      ".env와 월드·로그 파일은 Git에서 제외하며 사용자의 NAS 안에만 보관합니다.",
      "인터넷 공개 전에는 허용 목록을 활성화하고 NAS 관리·파일 서비스 포트를 외부에 열지 않습니다.",
      "외부 접속이 필요하면 직접 포트 개방보다 사설 메시 VPN을 우선하도록 안내합니다.",
    ],
  },
  {
    slug: "whattoeat",
    name: "오늘 뭐 먹지??",
    english: "What to Eat",
    eyebrow: "ONE GOOD MEAL, NEARBY",
    tagline: "오늘의 한 끼를, 가까운 곳에서.",
    summary: "현재 위치나 고른 지역을 기준으로 가까운 음식점 13곳을 추리고, 사진과 함께 오늘의 한 끼를 제안합니다. 전화번호가 있는 식당은 바로 전화해 영업 여부를 물을 수 있습니다.",
    theme: "coral",
    icon: "/apps/whattoeat/icon.png",
    artwork: "phones",
    platforms: [
      { name: "iPhone · iPad", status: "TestFlight", detail: "0.4.2 (202608271840) · iOS·iPadOS 17+", availabilityNote: "Public Beta 외부 심사 제출 · 승인 전까지 공개 링크에서는 0.4.1 제공" },
      { name: "Mac", status: "공개", detail: "0.4.1 (202608252106) · macOS 13+ · Universal · Apple 공증 완료", url: releaseDownloadPath("WhattoEat"), downloadLabel: "Mac용 DMG 다운로드", checksum: "b2387eab4b08056f06539c5dd4fdad59e223f48c4693d1e89c29bfa10c37f847", availabilityNote: "공증된 DMG 설치·실행 검증 완료" },
      { name: "Android · Google TV", status: "공개", detail: "0.4.3 · 빌드 202608291549 · 내부 코드 346549 · Android 8.0+", url: releaseDownloadPath("WhattoEat-Android"), downloadLabel: "Android용 APK 다운로드", checksum: "f94c4cfd5cc71645f94a5ba79053743d3d442b4fe83332f5f14579b5536c75a9", availabilityNote: "SM-F968N Android 16에서 동일 코드의 개발 빌드 교체 설치·실행, 단위 테스트와 공개 APK 릴리스 서명·해시 검증 완료 · 태블릿·TV 리모컨 검증 전" },
    ],
    features: [
      { title: "가까운 13곳에서 한 끼 고르기", body: "현 위치 또는 직접 고른 지역에서 가까운 음식점 13곳을 추린 뒤, 오늘의 한 끼와 함께 볼 맛집을 사진이 시원하게 보이는 2열 목록으로 보여줍니다." },
      { title: "기다리는 순간도 한 끼답게", body: "추천을 고르는 동안 음식 토큰과 주사위가 움직이는 애니메이션으로 선택의 기대감을 이어갑니다." },
      { title: "사진으로 먼저 맛보기", body: "Kakao Local에서 가까운 식당을 찾고 TourAPI의 검증된 식당 사진을 우선합니다. 사진이 없으면 Openverse에서 대표 메뉴와 이름을 함께 판단한 예시 사진을 찾아 빈 화면 없이 제안합니다." },
      { title: "원하는 지도 앱으로 바로", body: "네이버 지도, Apple 지도, 카카오맵과 Google 지도 중 하나를 정해 두고 식당 위치와 길 찾기를 이어갑니다." },
      { title: "영업 중인지 바로 전화하기", body: "전화번호가 있는 추천 식당은 원형 전화 버튼으로 바로 연결하고, 오늘의 결정에서는 번호도 함께 확인합니다." },
      { title: "가죽판에서 이어지는 선택", body: "첫 화면의 가죽 추천판을 제목 바로 아래에 두고 위치 선택 패널은 스티치 안쪽 폭에 맞췄습니다. 하단 메뉴는 같은 가죽 질감과 눌린 바늘 홈을 쓰고 추천 버튼 돌출부까지 스티치를 이었습니다." },
      { title: "점심 가방으로 바로 추천", body: "하단 중앙의 점심 가방을 누르면 새 추천을 시작합니다. 선택 중에도 원과 글자는 차분한 흰색을 유지하고 아래 빨간 막대만 보여 줍니다." },
      { title: "실내에서도 멈추지 않는 위치 찾기", body: "GPS가 느린 실내에서는 운영체제가 Wi-Fi와 셀룰러를 함께 활용해 위치를 찾습니다. 12초 안에 새 위치가 없으면 5분 이내의 최근 위치를 사용하고, 그것도 없으면 지역 직접 선택과 다시 시도로 바로 이어갑니다." },
      { title: "위치 권한을 놓쳐도 바로 복구", body: "첫 실행에서 위치 권한을 안내하고, 다시 묻지 않도록 거부한 경우에는 앱 설정에서 권한을 켜는 길을 바로 보여 줍니다. 권한을 바꾸고 돌아오면 보던 화면에서 위치 찾기를 이어갑니다." },
      { title: "상황에 맞는 메뉴와 지도 검색", body: "든든한 식사, 간단한 한 끼, 패스트푸드, 디저트·카페, 회식·모임, 야식 중 원하는 상황을 고르고 추천 메뉴를 선택한 지도 앱에서 바로 검색할 수 있습니다." },
      { title: "최근과 찜을 지역별로", body: "오늘 결정한 한 끼와 다시 가고 싶은 식당을 지역별로 모아 보고, 하트나 밀기로 간단히 정리합니다." },
      { title: "점심 전에 가볍게 알림", body: "점심시간과 몇 분 전에 받을지 정하면 이 기기에서 오늘의 한 끼 알림을 받을 수 있습니다." },
    ],
    guide: [
      { title: "지역 정하기", body: "현 위치를 다시 잡거나 지역 이름과 장소를 검색해 먹을 동네를 고릅니다." },
      { title: "메뉴 추천 받기", body: "추천 탭에서 가까운 후보와 사진을 보고, 아래로 내려 더 많은 식당을 살펴봅니다." },
      { title: "오늘은 여기로", body: "마음에 든 식당을 열어 지도와 정보를 확인한 뒤 오늘의 한 끼로 남깁니다." },
      { title: "다음 선택 이어가기", body: "최근과 찜에서 지역별 식당을 다시 보고, 필요 없는 항목은 바로 지웁니다." },
    ],
    progress: [
      { state: "done", title: "iPhone·iPad·Mac 앱 완성", body: "한 소스로 iPhone, iPad와 Mac Catalyst 화면·기능 구현" },
      { state: "done", title: "추천과 사진·지도 연결", body: "위치 기반 후보 선정, 메뉴 사진 대체, 외부 지도 앱 연결 구현" },
      { state: "done", title: "0.2.3 내부 테스트", body: "build 202608240838 iOS·iPadOS와 macOS를 내부 TestFlight 그룹에 배포" },
      { state: "done", title: "0.2.4 릴리스", body: "build 202608240930 iOS·iPadOS와 macOS TestFlight 처리 완료, 공증된 Mac용 DMG 공개" },
      { state: "done", title: "0.2.5 릴리스", body: "build 202608241232 iOS·iPadOS TestFlight 내부 테스트 준비 완료, Mac용 DMG 공개" },
      { state: "done", title: "0.2.6 전화 연결 릴리스", body: "build 202608241410 iOS·iPadOS TestFlight 업로드 완료 · Apple 처리 중, 공증된 Mac용 DMG 공개" },
      { state: "done", title: "0.3.0 가죽 화면 릴리스", body: "build 202608241540 iOS·iPadOS TestFlight 업로드 완료 · Apple 처리 중, 새 가죽 화면과 공증된 Mac용 DMG 공개" },
      { state: "done", title: "0.4.0 릴리스", body: "build 202608251921 iOS·iPadOS TestFlight 업로드, Apple 공증 Mac용 DMG 공개와 설치·실행 검증 완료" },
      { state: "done", title: "Android 0.4.0 공개", body: "제품 0.4.0 · 빌드 202608251400 · 내부 코드 340680 APK를 별도 공개 저장소에 게시하고 Android 16 휴대전화에서 데이터 유지 교체 설치·실행을 검증했습니다. 제품 버전 기준 자동 업데이트와 Android 8 화면 호환성도 함께 보완했습니다." },
      { state: "done", title: "0.4.1 점심 가방 내비게이션 릴리스", body: "build 202608252106 iPhone·iPad TestFlight 내부 테스트 준비, 공증된 Mac용 DMG와 Android 0.4.1 APK 공개를 완료했습니다. 선택 상태는 아래 빨간 막대만 표시하도록 모든 플랫폼을 맞췄습니다." },
      { state: "done", title: "Android 0.4.2 실내 위치 복구 공개", body: "build 202608271840 · 내부 코드 343840 APK를 공개했습니다. Wi-Fi·셀룰러를 포함한 기본 위치 공급자와 5분 이내 최근 위치를 활용하고, 실패해도 지역 직접 선택으로 이어집니다." },
      { state: "done", title: "Android 0.4.3 위치 권한 복구 공개", body: "build 202608291549 · 내부 코드 346549 APK를 공개했습니다. 첫 실행 권한 안내와 영구 거부 후 앱 설정 복구, 앱 복귀 뒤 현재 흐름 재개를 보완했습니다." },
      { state: "active", title: "iPhone·iPad 0.4.2 Public Beta 심사", body: "build 202608271840을 내부 테스트와 Public Beta 그룹에 연결하고 Apple 외부 베타 심사에 제출했습니다." },
      { state: "active", title: "태블릿·TV·접근성 후속 검증", body: "태블릿과 Google TV 리모컨, TalkBack 실제 읽기 순서, 밀기 후 재실행 저장과 지도 오류 분기를 실제 기기에서 추가 확인할 예정입니다." },
    ],
    screenshots: [
      { src: "/apps/whattoeat/screens/home.png", alt: "오늘 뭐 먹지 홈에서 현재 위치와 지역 선택을 고르는 화면" },
      { src: "/apps/whattoeat/screens/recommendation.png", alt: "오늘의 한 끼와 함께 보면 좋은 맛집을 사진으로 보여주는 추천 화면" },
      { src: "/apps/whattoeat/screens/decision.png", alt: "선택한 음식점 사진과 지도, 오늘은 여기로 버튼이 있는 결정 화면" },
      { src: "/apps/whattoeat/screens/region.png", alt: "현 위치 주변과 자주 찾는 지역을 보여주는 지역 화면" },
      { src: "/apps/whattoeat/screens/settings.png", alt: "지도 앱과 점심 알림을 정하는 설정 화면" },
      { src: "/apps/whattoeat/screens/android-bag-navigation.png", alt: "오늘 뭐 먹지 Android 추천 화면에서 점심 가방과 아래 빨간 선택 막대를 보여주는 화면" },
      { src: "/apps/whattoeat/screens/android-live-remote-results.png", alt: "오늘 뭐 먹지 Android에서 실제 외부 식당 사진과 전화 버튼을 보여주는 추천 결과" },
      { src: "/apps/whattoeat/screens/android-photo-information.png", alt: "오늘 뭐 먹지 Android 사진 정보에서 제공처와 제작자, 라이선스를 확인하는 화면" },
    ],
    github: ["https://github.com/armsone/WhattoEat", "https://github.com/armsone/WhattoEat-Android"],
    privacy: [
      "현재 위치는 주변 음식점 검색 요청에만 사용하며 앱 서버에 저장하지 않습니다.",
      "최근 한 끼, 찜, 자주 찾는 지역과 알림 설정은 사용자의 기기 안에 보관합니다.",
      "식당 검색과 사진 표시에는 카카오 로컬, 한국관광공사 TourAPI와 Openverse의 공개 데이터를 사용할 수 있으며 각 제공처의 정책이 함께 적용됩니다.",
      "지도 열기를 선택하면 사용자가 정한 외부 지도 앱으로 식당 이름과 위치가 전달됩니다.",
    ],
  },
  {
    slug: "denimdex",
    name: "데님덱스",
    english: "DenimDex",
    eyebrow: "DISCOVER THE VALUE IN DENIM",
    tagline: "당신의 데님, 가치를 발견하다.",
    summary: "빈티지 데님을 여러 각도에서 촬영하면 한양과 아이비가 제품 정보와 추정 생산연도·제조공장, 희귀도를 분석합니다. 한국·일본의 보수적인 적정 매입가와 근거를 확인하고 결과를 나만의 아카이브에 남길 수 있습니다.",
    theme: "blue",
    icon: "/apps/denimdex/icon.png",
    heroImage: "/apps/denimdex/denimdex-hero-v2.png",
    artwork: "phones",
    platforms: [
      {
        name: "iPhone · iPad",
        status: "TestFlight",
        detail: "0.2.1 (202608291110) · iOS·iPadOS 17+ · 외부 베타 심사 대기 중",
        availabilityNote: "감정 자동 스크롤·정사각형 사진·현재 버전 표시·ChatGPT 입력 안정화 빌드를 Internal과 Public Beta에 연결 완료 · Public Beta는 Apple 승인 뒤 참여 가능",
      },
      {
        name: "Android",
        status: "공개",
        detail: "0.2.1 · 빌드 202608291602 · 내부 코드 346562 · Android 8.0+",
        url: releaseDownloadPath("DenimDex-Android"),
        downloadLabel: "Android용 APK 다운로드",
        checksum: "38c7585761ffe2431a2285a94bdac1c56557aceb39ee34fd8c64c37ffb728d11",
        availabilityNote: "SM-F968N Android 16에서 동일 코드 개발 빌드 데이터 보존 설치·실행, 72개 단위 테스트와 공개 APK 전용 서명·해시 검증 완료 · 태블릿·TV 검증 전",
      },
    ],
    features: [
      { title: "한 벌을 최대 30장의 디테일로", body: "전체 실루엣부터 패치, 레드탭, 버튼, 봉제와 케어라벨까지 자유롭게 촬영하거나 보관함에서 고릅니다. 길게 눌러 중요한 순서로 바꾸고 한 번에 모두 비울 수 있습니다." },
      { title: "한양이 비슷한 사진을 먼저 정리", body: "원본 30장은 그대로 두고, 한양이 겹치는 구도와 품질을 살펴 분석에 도움 되는 사진을 최대 20장으로 추립니다.", icon: "/apps/hanai/icon.png" },
      { title: "아이비로 이어지는 ChatGPT 감정", body: "별도 API 키 없이 사용자가 공식 ChatGPT 화면에서 직접 로그인한 웹 세션을 활용합니다. 로그인이 필요하면 앱 안에서 안내하고, 완료된 분석 결과만 데님덱스로 가져옵니다.", icon: "/apps/aibi/icon.png" },
      { title: "제품 정보와 생산 단서를 먼저", body: "사진에서 확인한 브랜드·모델과 함께 추정 생산연도, 추정 제조공장, 그 판단에 사용한 라벨·버튼·리벳·봉제 단서를 구분해 보여줍니다." },
      { title: "근거에 맞춘 보수적 희귀도", body: "단종 여부와 생산 시기, 세부 사양처럼 사진으로 뒷받침되는 요소를 중심으로 희귀도를 평가합니다. 근거가 부족하면 과감히 판단을 보류합니다." },
      { title: "한국과 일본의 적정 매입가를 나란히", body: "제품 정보와 상태, 희귀도를 바탕으로 과도한 기대가를 피한 적정 매입 범위를 한국 원화와 일본 엔화로 함께 보여줍니다." },
      { title: "팔았을 때 남는 금액까지", body: "예상 판매가에서 시장별 수수료와 배송비를 반영한 순수익을 계산하고, 일본에서 사서 한국에 팔거나 반대로 거래할 때의 예상 차익도 손해 구간까지 숨김없이 표시합니다." },
      { title: "판단 근거와 확실성을 함께", body: "제품명만 단정하지 않고 사진에서 직접 확인한 특징, 추정한 내용과 신뢰 수준을 구분해 보여줍니다. 실시간 거래 시세가 아닌 AI 기반 참고 범위라는 한계도 함께 안내합니다." },
      { title: "나만의 데님 아카이브", body: "감정 결과와 고른 사진을 기기 안 개인 아카이브에 저장해 다시 확인하고, 필요 없는 기록은 직접 삭제할 수 있습니다." },
      { title: "사진은 가볍게, 단서는 선명하게", body: "선택 장수가 많아질수록 전송용 사본의 크기와 품질을 단계적으로 조절해 전체 용량을 약 16MB 안으로 맞춥니다. 원본 사진은 변경하지 않습니다." },
      { title: "작성 중인 글은 그대로 보호", body: "ChatGPT 입력창에 다른 글이 있으면 덮어쓰지 않고 멈춥니다. 빈 입력창에서도 실제로 요청이 들어갔는지 확인한 뒤 다음 단계로 넘어가며, 사진을 읽지 못해도 앱을 닫지 않고 다시 고를 수 있습니다." },
    ],
    guide: [
      { title: "사진 담기", body: "데님의 전체 앞·뒤 모습과 패치, 탭, 버튼, 리벳, 봉제, 케어라벨처럼 서로 다른 단서를 촬영하거나 사진 보관함에서 선택합니다." },
      { title: "중요한 순서로 정리", body: "사진을 길게 눌러 드래그하고, 전체 모습과 식별 정보가 잘 보이는 사진을 앞쪽에 둡니다. 비슷한 사진은 한양이 분석 전에 다시 정리합니다." },
      { title: "가치 확인하기", body: "가치 확인하기를 누릅니다. ChatGPT 로그인이 필요하면 공식 로그인 화면에서 직접 로그인한 뒤 분석을 이어갑니다." },
      { title: "핵심 감정 정보 확인", body: "제품 정보, 추정 생산연도·제조공장, 희귀도와 한국·일본 적정 매입가를 사진 근거 및 신뢰 수준과 함께 확인합니다." },
      { title: "아카이브에 저장", body: "다시 보고 싶은 결과를 개인 아카이브에 저장합니다. 현재 기록과 원본 사진은 사용자의 기기 안에 보관됩니다." },
    ],
    progress: [
      { state: "done", title: "다중 사진 감정 흐름", body: "최대 30장 추가·재정렬·전체 비우기와 한양 기반 유사 사진 정리, 최대 20장 AIBI 분석 구현" },
      { state: "done", title: "한·일 가치와 차익 계산", body: "한국·일본 예상 판매가, 수수료·배송비를 반영한 순수익과 양방향 시장 차익 표시 구현" },
      { state: "done", title: "개인 아카이브", body: "감정 결과와 사진을 기기 안에 저장하고 다시 보거나 삭제하는 흐름 구현" },
      { state: "active", title: "iPhone·iPad 0.2.1 Public Beta 심사", body: "사진 등록 후 가치 확인 버튼과 분석 진행 화면 자동 스크롤, 정사각형 사진, 현재 버전 표시와 ChatGPT 입력 재시도를 담은 build 202608291110을 기존 Internal과 Public Beta 그룹에 연결하고 외부 베타 심사에 제출했습니다. 공개 링크는 Apple 승인 뒤 신규 참여가 가능합니다." },
      { state: "done", title: "Android 0.2.1 첫 공개", body: "build 202608291602 · 내부 코드 346562 APK를 공개했습니다. 인증된 ChatGPT 세션 판정, 기존 입력 보호, 네 번의 입력 확인, 사진 준비 실패 복구와 자동 스크롤을 포함합니다." },
      { state: "next", title: "아카이브 동기화", body: "개인 NAS 연결과 익명 기록 공유는 준비 중이며 현재 공개 기능에 포함하지 않음" },
    ],
    screenshots: [
      { src: "/apps/denimdex/screens/home.png", alt: "데님덱스에서 빈티지 데님의 한국과 일본 시장 가치를 소개하는 감정 홈 화면" },
    ],
    github: ["https://github.com/armsone/DenimDex-iOS", "https://github.com/armsone/DenimDex-Android"],
    privacy: [
      "원본 사진과 저장한 감정 기록은 기본적으로 사용자의 기기 안에 보관됩니다.",
      "가치 확인을 시작하면 한양이 고른 사진의 전송용 사본과 분석 요청이 사용자가 로그인한 ChatGPT 공식 웹사이트로 전달됩니다. 전송용 사본은 작업이 끝나면 앱에서 폐기됩니다.",
      "DenimDex는 ChatGPT 비밀번호와 로그인 쿠키를 읽거나 별도 서버에 저장하지 않습니다. 로그인은 ChatGPT 공식 화면에서 사용자가 직접 진행합니다.",
      "한국·일본 가격과 차익은 사진 및 일반 시장 지식에 기반한 참고 추정치이며 실시간 거래 데이터나 실제 판매 수익을 보장하지 않습니다.",
      "개인 NAS 기반 아카이브 동기화는 준비 중이며 현재 버전에서는 사용하지 않습니다.",
    ],
  },
  {
    slug: "aibi",
    name: "아이비",
    english: "AIBI",
    eyebrow: "SAFE AI, INSIDE YOUR APP",
    tagline: "앱과 공식 AI 사이를, 안전하게.",
    summary: "아이비는 사용자가 직접 로그인한 Gemini·ChatGPT·Claude 공식 웹 세션을 앱 안에서 안전하게 이어 쓰는 공통 엔진입니다. 제공자 화면이 바뀌어도 앱 고유 화면과 결과 흐름은 지키며 업데이트합니다.",
    theme: "blue",
    icon: "/apps/aibi/icon.png",
    heroImage: "/apps/aibi/aibi-hero-v2.png",
    spotlightImage: "/apps/aibi/aibi-hero-v2.png",
    artwork: "bridge",
    platforms: [
      {
        name: "StarManager · iOS · Android",
        status: "공개",
        detail: "AIBI 0.4.4 · Apple·Android 공통 엔진 · StarManager 동기화 완료",
        url: "https://github.com/armsone/AIBI/releases/download/v0.4.4/AIBI-0.4.4.zip",
        downloadLabel: "AIBI 0.4.4 소스 받기",
        checksum: "0f67bbceb91c1d069d9224267a7b43b1ecb8aafe5e6973af79732c28371f7621",
        availabilityNote: "독립 소스 공개 · StarManager에는 검증된 같은 엔진 포함",
      },
    ],
    features: [
      { title: "내 계정은 공식 페이지에 그대로", body: "비밀번호·쿠키·토큰을 복사하거나 저장하지 않고 사용자가 각 AI 공식 웹사이트에서 직접 만든 로그인 세션만 브라우저 표준 저장소로 재사용합니다." },
      { title: "필요할 때만 나타나는 AI 브라우저", body: "평소에는 작성 화면을 유지하며 진행 상태를 보여주고, 로그인·보안 확인처럼 사용자가 직접 해야 하는 순간에만 같은 작업을 보이는 브라우저로 안전하게 넘깁니다." },
      { title: "완성된 답만 정확히 한 번", body: "입력과 실제 전송을 확인하고 스트리밍 결과가 안정될 때까지 관찰한 뒤, 호스트 앱의 검증을 통과한 최종 결과만 한 번 반영합니다." },
      { title: "사진을 순서대로, 빠짐없이", body: "기본 8장, 앱이 명시적으로 허용하면 최대 20장까지 순서를 유지해 전달합니다. 원본은 바꾸지 않고 긴 변 2,048px·장당 2MB 안의 전송용 사본만 차례대로 만듭니다." },
      { title: "로그아웃과 재로그인까지", body: "각 서비스의 로그인 상태를 다시 확인하고, 앱 전용 웹 세션을 모두 로그아웃한 뒤 필요한 계정으로 다시 로그인할 수 있습니다." },
      { title: "기다림과 취소가 분명하게", body: "생성 뒤 1분 59초의 남은 시간과 감소하는 진행 막대를 보여주며, 숨김·보이기 화면 어디서든 취소하면 작업과 브라우저를 즉시 정리합니다." },
      { title: "제공자 변화는 어댑터에서만", body: "Gemini·ChatGPT·Claude의 화면 구조 변화는 제공자별 선택자와 회귀 자료에 격리해 공통 상태 기계와 앱 결과 흐름을 흔들지 않습니다." },
      { title: "앱별 수정은 덮어쓰지 않는 업데이트", body: "버전과 SHA-256 잠금으로 이식 파일을 관리합니다. 앱에서 따로 수정한 파일이 발견되면 자동 업데이트를 멈추고 충돌을 먼저 조정합니다." },
    ],
    guide: [
      { title: "앱에서 AI 선택", body: "StarManager에서 Gemini·ChatGPT·Claude 중 하나를 누르면 별도 확인 단계 없이 아이비 작업이 시작됩니다." },
      { title: "공식 페이지에서 직접 로그인", body: "로그인이 필요하면 앱 안에 열린 제공자 공식 페이지에서 사용자가 직접 로그인합니다. 성공이 확인되면 화면은 자동으로 닫힙니다." },
      { title: "진행 또는 브라우저 보기", body: "기본 모드에서는 앱 화면의 단계·남은 시간·취소를 확인합니다. 브라우저 보기를 켜면 입력부터 결과 생성까지 공식 화면을 처음부터 볼 수 있습니다." },
      { title: "검증된 결과 받기", body: "생성이 끝나고 결과가 안정되면 StarManager의 문체와 길이 규칙을 확인해 본문에 반영하고 브라우저를 정리합니다." },
    ],
    progress: [
      { state: "done", title: "독립 기준 프로젝트 0.4.4 공개", body: "공통 계약, 제공자 변화 대응 절차, Apple·Android 엔진과 StarManager 배포 스냅샷을 검증해 독립 소스 릴리즈로 공개" },
      { state: "done", title: "다중 사진 파이프라인", body: "Apple·Android·브라우저 런타임에서 최대 8장의 이미지 순서와 첨부 확인을 같은 계약으로 검증" },
      { state: "done", title: "최대 20장 선택과 입력창 복구", body: "앱별 선택으로 최대 20장을 원자적으로 첨부하고, 공식 AI 화면이 입력창을 늦게 교체해도 내용을 보존해 다시 입력하도록 개선" },
      { state: "done", title: "StarManager iOS 이식", body: "공유 WKWebView 세션, 숨김·보이기 실행, 로그인 판정, 결과 안정화, 1:59 제한과 취소 흐름을 빌드 검증" },
      { state: "done", title: "StarManager Android 이식", body: "EXIF 방향 보정·순차 축소·FileProvider 다중 첨부·숨김 키보드 정리와 로그인 관리를 연결하고 3대의 Android 기기에서 배포 빌드 설치·실행 검증" },
      { state: "done", title: "충돌 방지 업데이트", body: "등록 앱 전체 사전 점검, SHA-256 잠금, 원자적 복사와 앱 로컬 수정 보호를 자동화" },
      { state: "active", title: "제공자 변화 회귀 자료 확대", body: "개인정보를 제거한 로그인·생성 중·완료·오류 fixture와 실기기 추적을 제공자별로 축적" },
    ],
    github: ["https://github.com/armsone/AIBI"],
    privacy: [
      "비밀번호, 쿠키 값, 세션 토큰, 원문 프롬프트와 전체 생성 답변을 수집·저장·로그로 남기지 않습니다.",
      "로그인과 실행 브라우저는 운영체제의 표준 영구 웹 저장소를 공유하며 로그인은 각 제공자 공식 페이지에서 사용자가 직접 수행합니다.",
      "자동화 스크립트는 허용된 공식 실행 origin에만 주입하고 OAuth·결제·제3자 페이지에는 주입하지 않습니다.",
      "기록 가능한 진단은 제공자, 단계, 소요 시간, 익명 실패 코드와 결과 길이처럼 원문을 포함하지 않는 값으로 제한합니다.",
    ],
  },
];

export function findApp(slug: string) {
  return apps.find((app) => app.slug === (slug === "backtonormal" ? "btn" : slug));
}
